### ISSUE TITLE
MySMS not signing in

### ISSUE THREAD

**Issue by dgallo12** [meetfranz/franz#559] opened 2018-01-10 17:08 UTC
### Expected Behavior
The gmail sign-in feature should load relatively fast after putting in sign-in information

### Current Behavior
The window is stuck saying "one moment please" after putting in google credentials and pressing "sign in."

### Steps to Reproduce (for bugs)

1. add mySMS to client
2. click sign in with google
3. enter google credentials
4. press sign-in 

### Context
Cannot sign into MySMS through Gmail to send texts from the Franz client.

### Your Environment

* Franz Version used: latest version
* Operating System and version: Windows 10 fully updated

**Comment by haraldox** [comment] 2018-01-15 13:42
Duplicate of #408

**Closed by haraldox** 2018-01-15 13:42 UTC
Labels: links [temp], service
