### ISSUE TITLE
Franz opens off screen edges

### ISSUE THREAD

**Issue by dVerhees** [meetfranz/franz#495] opened 2017-12-22 07:03 UTC
When I open Franz for the first time every day it tries to open it on my second screen even if the second screen is not connected. In addition when the second screen is not to the right but below the first screen it still opens on the right side of my first screen

### Expected Behavior
Franz should open on an active screen or the position you last used it. Not reset to a position that is no longer available

### Current Behavior
Franz opens off screen the window is not reachable using the mouse.

### Possible Solution
It looks like Franz is using a fixed position to open the window, suggestion would be that it would open on the first monitor.

### Steps to Reproduce (for bugs)
1. Start computer
2. Open Franz

### Context
Every time I use Franz (every day) for the first time I have to use key commands to move the window back to a visible position. (ALT + SPACE) then press R and move the window with the arrow keys.

### Your Environment
* Franz Version used: Franz 5.0.0 Beta 14
* Operating System and version: Windows 10 Pro

**Comment by CevG33ko** [comment] 2018-01-24 11:52
This annoying me too! at least i got a temporary solution here(Thanks to dVerhees and not the Franz suport). 
Still very nerve wrecking issue!

**Comment by janacm** [comment] 2018-01-30 02:52
Me too - Windows 10

**Comment by haraldox** [comment] 2018-02-13 13:10
@janacm do you mean the shortcut for disabling notifications and audio ctrl+shift+m?

 i'm intrigued as to what workaround that is? :) i'm assuming you're on Windows?

**Comment by haraldox** [comment] 2018-02-13 13:10
merging this into #222 

Duplicate of #222

**Comment by haraldox** [comment] 2018-02-13 13:10
merging this:

Duplicate of #222

**Comment by haraldox** [comment] 2018-02-13 13:11
Duplicate of #222

**Closed by haraldox** 2018-02-13 13:10 UTC
Labels: os/windows

**Comment by jakelauer** [comment] 2018-02-13 15:47
@janacm I think the shortcut is actually alt+space, then M
