### ISSUE TITLE
Franz helper 84% CPU

### ISSUE THREAD

**Issue by Andili59** [meetfranz/franz#31] opened 2017-10-19 14:27 UTC
Franz Helper uses up to 84 % of the CPU
![screen shot 2017-10-19 at 16 18 17](https://user-images.githubusercontent.com/32933926/31775870-1fb861a2-b4ea-11e7-9216-31f4387437ff.png)

Version 5.0.0-beta.10 (5.0.0-beta.10.7) , OSX 10.12.6, iMac (27-inch, Late 2013)

**Comment by adlk** [comment] 2017-10-19 14:39
Duplicate of #24

**Closed by adlk** 2017-10-19 14:39 UTC
