### ISSUE TITLE
Emoji button on Touch Bar

### ISSUE THREAD

**Issue by gthibaud** [meetfranz/franz#576] opened 2018-01-15 11:41 UTC
### Feature Description
I find very useful the emoji button on the Touch Bar (like we can view it on the Messages app, or when writing text on MacOs), so I was wondering if it was possible to possibly integrate it on Franz app.

### Motivation and Context
The emoji Touch Bar button is very useful when writing long messages. It will be easier to have it maybe on the left of the services button.

### Screenshots:
Actual Touch Bar when writing message : 
<img width="1085" alt="capture d ecran touch bar 2018-01-15 a 06 32 42" src="https://user-images.githubusercontent.com/27550148/34940708-9c192254-f9be-11e7-9c4c-eeef8178542d.png">
What would be nice :
<img width="1085" alt="capture d ecran touch bar 2018-01-15 a 06 35 18" src="https://user-images.githubusercontent.com/27550148/34940735-b3ec8286-f9be-11e7-9dea-f41ca6cff193.png">

Thank you for your consideration ! 
Best regards,

Grégoire Thibaud

**Comment by haraldox** [comment] 2018-01-15 11:45
@gthibaud bonjour Grégoire: that would be a welcome addition but i'm afraid that in order to work there would be service-specific issues. most services already accept shortcuts for smileys (e.g. beginning with *:* on whatsapp), or transform them automatically (e.g. facebook messenger)

does that satisfy you in the meantime?

**Comment by haraldox** [comment] 2018-01-15 11:45
Duplicate of #550

**Closed by haraldox** 2018-01-15 11:45 UTC

**Comment by BorBorBor** [comment] 2018-11-09 23:29
To be honest, this is not a satisfying solution as there is a difference between for instance the shortcut in Whatsapp @haraldox and the system-wide emoji interface in macOS. 

I'm not sure what the issue is but it seems Franz overrides all touch bar usage, for instance text prediction is also not working. If I use Whatsapp Web, Telegram Web, Slack etc natively or in Safari the emoji button works fine. Apparently that's also the case if you're commenting on Github 👌😃😉
