### ISSUE TITLE
2 versions coexisting

### ISSUE THREAD

**Issue by lexaliemu** [meetfranz/franz#288] opened 2017-11-16 19:35 UTC
Sometimes I have the normal version (http://d.pr/i/HMj4Tg)  and sometimes I have an other one (http://d.pr/i/gRy5HT) which is a pain in the b...
When I relaunch sometimes it works, sometimes it doesn't. Can't find pattern.

This crappy version is difficult to use as when you're in a conversation, you don't have the left side bar with others conversations and the search bar. You need either to go back or to click on search logo.

**Comment by adlk** [comment] 2017-11-16 19:51
I don't really get the issue? Can you please use the initial issue template, provide all necessary information and explain what the issue is?

**Comment by kristofm** [comment] 2017-11-24 14:21
@adlk I think what he means is that the installation for 5.0.0 does not actually remove the old version (4.0.4)(like you would expect of a software when a new one is released), or at least this is the case on windows.

**Comment by adlk** [comment] 2017-11-24 14:31
Franz 5 is not yet supposed to forcefully replace the old version as we are still facing a lot of issues. The user should be able to decide which version he/she wants to use.

**Comment by BrianGilbert** [comment] 2017-12-05 20:24
@lexaliemu 

Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by haraldox** [comment] 2018-01-15 14:10
@lexaliemu do you still face the same issue?

closing this for now, feel free to reopen the issue with any questions or comments!

**Closed by haraldox** 2018-01-15 14:10 UTC
Labels: incomplete, more information required
