### ISSUE TITLE
Google services no longer loading (Gmail/Calendar)

### ISSUE THREAD

**Issue by incace** [meetfranz/franz#1499] opened 2019-06-22 13:55 UTC
**Describe the bug**
On app launch, Gmail and Calendar services never load or initiate. Just a blank screen with no sign of anything.

**To Reproduce**
1. Start Franz
2. Wait...
3. Every service loads except Gmail and Calendar
4. Reload services
5. Still nothing...

**Expected behavior**
Services to load as per normal.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6

**Comment by incace** [comment] 2019-06-22 13:55
Restarting Franz does not fix the issue.

**Comment by Wouter0100** [comment] 2019-06-22 20:03
Duplicate of #1483. See for a temporarily the this issue.

**Closed** 2019-07-11 19:57 UTC
