### ISSUE TITLE
Mute not working on WhatsApp

### ISSUE THREAD

**Issue by filipeabperes** [meetfranz/franz#742] opened 2018-02-27 21:42 UTC
### Current Behavior

Both disabling audio and using the global mute button (bell on lower left corner) does not work on WhatsApp, which still produces audio pings on incoming messages (and is able to reproduce sounds from clips, videos, etc.)

### Your Environment

* Franz Version used: 5.0.0-beta.16
* Operating System and version: Mac OS High Sierra 10.13.3

**Comment by filipeabperes** [comment] 2018-02-28 05:02
For some reason had not seen [this issue](https://github.com/meetfranz/franz/issues/733) first time I searched. Sorry for the duplicate.

**Comment by haraldox** [comment] 2018-02-28 14:16
Duplicate of #733

**Closed by haraldox** 2018-02-28 14:16 UTC
Labels: tmp/notifications
