### ISSUE TITLE
Allow Resizing Side-Bar

### ISSUE THREAD

**Issue by harshilsharma63** [meetfranz/franz#602] opened 2018-01-22 12:19 UTC
Allow resizing sidebar to make it better suit various screen size and user preferences. I have a 14-inch laptop and the sidebar is just too big and consumes precious screen real-estate.

### Expected Behavior
Hovering over right-edge of sidebar should allow resizing sidebar horizontally.

### Current Behavior
Sidebar width is not customizable and may look bad on small screens.

### Context
Current side-bar width is too much for my 14-inch screen. In the pursuit to save screen space, I wish the width was configurable.

### Your Environment
* Franz Version used: 5.0.0-beta.15
* Operating System and version: Ubuntu 16.04 64 bit

**Comment by roycifer** [comment] 2018-01-23 06:56
i too am on a small screen (11-inch macbook air) and would like to see a smaller sidebar. i know on a mac, the traffic light buttons consume the width of the sidebar so perhaps an alternative would be to have a top bar option. here is a screenshot of a sample ive made using the vivaldi browser with top-pinned tabs for email and chat apps...

![screen shot 2018-01-22 at 10 55 49 pm](https://user-images.githubusercontent.com/320397/35261979-6ba31b84-ffc7-11e7-8889-81b37664f0ff.png)

**Comment by harshilsharma63** [comment] 2018-01-23 07:32
BTW I gave up on Franz 5 yesterday when I found using self-hosted Mattermost required paid version of Franz.

**Comment by haraldox** [comment] 2018-02-14 14:18
@roycifer this is on our list

**Comment by haraldox** [comment] 2018-02-14 14:19
Duplicate of #156

**Closed by haraldox** 2018-02-14 14:19 UTC
