### ISSUE TITLE
Switch Languages 

### ISSUE THREAD

**Issue by fahmawy** [meetfranz/franz#492] opened 2017-12-20 16:26 UTC
its too silly to show the menu after you press alt+shift to change current lang iam using linux mint
btw other programs works fine but franz need to switch then press scape tyo cancel the short menu of edit then write

### Steps to Reproduce (for bugs)

1. open franz
2.write message or mail whatever
3.switch lang to write with any lang 
4.you will meet what i meant 

### Context

This made me lose time cause i suggest that iam write but it waiting for esc to remove the menu 
### Your Environment

* Franz Version used:
* Operating System and version: Linux mint

**Comment by adlk** [comment] 2017-12-21 11:11
I'm actually not able to follow you.

**Comment by fahmawy** [comment] 2017-12-21 11:36
why :D 

on switching languages that makes the file menu in franz opened that makes you to press cancel before you write again

**Comment by adlk** [comment] 2017-12-21 11:44
Now I get it. Thank you for clarification, see there is a difference between changing the language of e.g Franz or the keyboard language.

**Comment by adlk** [comment] 2017-12-21 11:44
Duplicate of #387

**Closed by adlk** 2017-12-21 11:44 UTC
Labels: more information required
