### ISSUE TITLE
Window size/location not retained

### ISSUE THREAD

**Issue by Kevin-** [meetfranz/franz#728] opened 2018-02-25 16:29 UTC
### Expected Behavior
Remember window location and monitor placement.

### Current Behavior
Does not remember window size or location, or which monitor it is on.

### Steps to Reproduce (for bugs)
1. Move to 2nd or 3rd monitor.
2. Close
3. Restart.

### Your Environment

* Franz Version used: 5.0.0-beta.16
* Operating System and version: Windows 10 Pro 1709 build 16299.248

**Comment by andela-jomadoye** [comment] 2018-02-25 19:33
Same here, my issue started after I updated to version 5.0.0-beta.16.762

**Comment by Kevin-** [comment] 2018-02-27 13:37
Hmm starting today this problem seems to have gone away (without upgrading).  Upon startup my window size/location is now retained.

**Comment by haraldox** [comment] 2018-02-28 13:55
Duplicate of #222

**Closed by haraldox** 2018-02-28 13:55 UTC
