### ISSUE TITLE
Opening Franz while already running opens new instance

### ISSUE THREAD

**Issue by rutgerkra** [meetfranz/franz#73] opened 2017-10-23 10:05 UTC
### Expected Behavior

Starting with Franz already opened,I expect to open the currently running instance of Franz when clicking on a Franz shortcut from anywhere in my system (start menu, taskbar shortcut, etc.)

### Current Behavior

If Franz is already running and I click on a shortcut, I open a new instance, suddenly having multiple instances of Franz running simultaneously, instead of presenting the already running instance.

### Screenshots (if appropriate):
![Multiple instances](https://puu.sh/y52Da/863abfe8db.png)

### Steps to Reproduce (for bugs)

1. Open Franz
2. Open Franz again

### Your Environment

* Franz Version used:
* Operating System and version:
Running Windows 10 latest update

**Comment by adlk** [comment] 2017-10-23 10:06
Duplicate of #29

**Closed by adlk** 2017-10-23 10:06 UTC
