### ISSUE TITLE
Franz v5 Mac: WeChat Fails

### ISSUE THREAD

**Issue by dustylolo** [meetfranz/franz#493] opened 2017-12-20 18:42 UTC
The latest Franz v5 for Mac doesn't work with WeChat, the scan bar code for desktop fails to load. Please have this fixed. Much appreciated

### Expected Behavior
Expects to see a desktop scan bar code for connecting through the mobile app account

### Current Behavior
Bar code fails to load

### Your Environment
* Franz Version used: v5.0.0 beta 14
* Operating System and version: Mac Sierra 10.13.2

**Comment by BrianGilbert** [comment] 2017-12-20 22:47
This should be oin the service repo (https://github.com/BrianGilbert/franz-recipe-wechat), however I'm unable to reproduce, so am closing the issue.

![franz 2017-12-21 09-45-58](https://user-images.githubusercontent.com/114017/34232315-df22786e-e633-11e7-9b01-ab5c25caf82a.png)

**Closed by BrianGilbert** 2017-12-20 22:47 UTC

**Comment by koma-private** [comment] 2018-01-16 08:10
@BrianGilbert 
> This should be on the service repo

Partially yes. The franz repo is intended to talk about the client, not services.
FYI you have to raise PRs to Franz's official plugin repo after creating recipes
but the WeChat recipe is already registered with my version (please also check the date) https://github.com/meetfranz/plugins/issues/43

So questions and requests should be redirected to my repo, to avoid any confusion.
https://github.com/koma-private/recipe-wechat

**Comment by BrianGilbert** [comment] 2018-01-16 08:14
@koma-private More than happy for yours to be the main one, will remove mine.

**Comment by koma-private** [comment] 2018-01-16 08:24
@BrianGilbert Anyway thank you for contribution ;) I should check messages and reply to them more often. I think currently it's difficult for end-users to find appropriate place to ask about recipes because they have to search for original authors by checking PRs at the plugin repo.
