### ISSUE TITLE
Can't use command of copy and paste

### ISSUE THREAD

**Issue by liencode** [meetfranz/franz#660] opened 2018-02-07 00:55 UTC
### Expected Behavior
If I used ⌘+C, selected text copied.

### Current Behavior
If I used ⌘+C, selected text dosen't copied.

### Your Environment
* Franz Version used: 5.0.0
* Operating System and version: Mac OSX 10.11.6

**Comment by jacoblo** [comment] 2018-02-07 09:27
Same problem here. Very annoying and think it worked before.

**Comment by OArnarsson** [comment] 2018-02-07 11:37
Possible duplicate of https://github.com/meetfranz/franz/issues/33?

**Comment by jacoblo** [comment] 2018-02-08 12:53
@OArnarsson Running beta.15, beta versions (obviously) enabled and tried restarting multiple times :(

**Comment by haraldox** [comment] 2018-02-13 14:48
Duplicate of #33

**Closed by haraldox** 2018-02-13 14:48 UTC

**Comment by Joejoboi** [comment] 2018-09-30 21:40
Can we open this one back up? It appears to still be a challenge.
