### ISSUE TITLE
After leaving Franz idle, all screens are blank

### ISSUE THREAD

**Issue by JayM1212** [meetfranz/franz#591] opened 2018-01-18 00:32 UTC
Having a common issue when using Franz!

After leaving Franz idle for some time, or often putting my windows computer to sleep and coming back to it later - all the app screens are completely blank.  An additional issue with this, is that when I try to close the app from the toolbar...it doesn't work. I have to manually go into the Task Manager and "End Process" of Franz running in the background.

This becomes increasingly more annoying when having to respond to something quickly! Not sure if anyone is having the same issue.

**Comment by haraldox** [comment] 2018-01-18 09:48
Duplicate of #594

**Closed by haraldox** 2018-01-18 09:48 UTC
