### ISSUE TITLE
Add capability to log in to multiple slack channels in franz app

### ISSUE THREAD

**Issue by goleary** [meetfranz/franz#430] opened 2017-12-08 19:40 UTC
When I click 'sign in to another workspace' on slack within franz it opens in a browser window and after logging in I see no effect to slack within franz.

Would be awesome to get this functionality so I don't have to continue using slack web/desktop for my non-primary slack channel.

**Comment by alecive** [comment] 2017-12-08 21:40
Duplicate of https://github.com/meetfranz/franz/issues/391 . See my reply there. You just need to open multiple recipes within franz and you will not have to switch any more.

**Comment by adlk** [comment] 2017-12-11 09:23
@goleary @alecive's answer is the way to go.

_Note to myself:_ I might need to remove the "add another workspace" option...

**Closed by adlk** 2017-12-11 09:23 UTC
