### ISSUE TITLE
Services stop after waking up from suspend

### ISSUE THREAD

**Issue by codesome** [meetfranz/franz#644] opened 2018-02-02 14:56 UTC
### Expected Behavior

When system wakes up from suspend I expect all the service to be still running.

Suspending a laptop is very normal and frequent. 

### Current Behavior

After waking up from suspend, all the services are blank (not running) except one of them. I need to reload all the services to get it running. I don't know if this is a bug or feature, would like to know.

### Screenshots:
![screenshot from 2018-02-02 19-34-10](https://user-images.githubusercontent.com/15064823/35738973-4a497e82-0856-11e8-9e92-99e0cc7a9352.png)
![screenshot from 2018-02-02 19-34-07](https://user-images.githubusercontent.com/15064823/35738968-4565d3ac-0856-11e8-93fe-efc824ef01a7.png)
![screenshot from 2018-02-02 19-34-04](https://user-images.githubusercontent.com/15064823/35738961-3fe87af6-0856-11e8-9e15-3071efb1bbc8.png)
![screenshot from 2018-02-02 19-33-57](https://user-images.githubusercontent.com/15064823/35738952-3594dfd6-0856-11e8-8cfa-cfa061dd4771.png)

### Steps to Reproduce

(not sure if it happens for everyone)
1. Open multiple services
2. Suspend your system
3. Turn on system

### Context

1. I don't get to know about new notifications as the service is down. Some of them can be really urgent.
2. Have to manually reload service everytime I suspend and open, which is annoying.

### Your Environment

* Franz Version used: 5.0.0-beta.15
* Operating System and version: Ubuntu 16.04.3 LTS, Linux x86_64 4.4.8-040408-generic

**Comment by haraldox** [comment] 2018-02-03 09:12
@codesome this is a known issue, while we fix it you can reload all services by pressing ctrl+shift+R in the meantime

**Comment by haraldox** [comment] 2018-02-03 09:12
Duplicate of #594

**Closed by haraldox** 2018-02-03 09:12 UTC

**Comment by carestad** [comment] 2018-04-23 07:38
Was this fixed? I am having issues again with this in beta 18 in Ubuntu. It was working in beta 16 or 17 (services were refreshed after waking up from suspended state).

**Comment by imnotteixeira** [comment] 2019-01-04 13:42
Is there some update to this? I am using beta 18 with ubuntu 18.04 and it still happens

**Comment by closingin** [comment] 2019-01-04 14:49
I didn't check the release notes, but it's beta 21 now. Try to update maybe ?
