### ISSUE TITLE
indicator icon is not visible with dark themed panel (Linux, xfce 4) and no icon for application

### ISSUE THREAD

**Issue by as3mbus** [meetfranz/franz#395] opened 2017-12-03 14:16 UTC
is there any option to change the icon for indicator panel since dark theme hide it
and also adding your own icon for franz app wont show it icon on window buttons
it only work with launcher icon  

### Expected Behavior
indicator icon should be visible

### Current Behavior
indicator icon not visible with dark colored panel

### Screenshots (if appropriate):
Indicator
![image](https://user-images.githubusercontent.com/16043293/33526110-3f79d9a6-d86e-11e7-9c90-759f13958ce1.png)
Window Buttons
![image](https://user-images.githubusercontent.com/16043293/33526147-30fcd314-d86f-11e7-942a-37199509c25f.png)

### Possible Solution
assign icon that could be themed with icons directory 
some help to fix this

### Steps to Reproduce (for bugs)
1. install latest franz from deb (main website link)
2. use dark theme on panel (xfce 4)

### Context
more adaptive indicator icon

### Your Environment

* Franz Version used: 5.0.0 beta 14
* Operating System and version: XUbuntu 16.04

**Comment by adlk** [comment] 2017-12-03 18:57
Duplicate of #233

**Closed by adlk** 2017-12-03 18:57 UTC
