### ISSUE TITLE
Whatsapp crashing on image upload.

### ISSUE THREAD

**Issue by chanakyashah** [meetfranz/franz#611] opened 2018-01-25 06:12 UTC
I expected Whatsapp to work exactly like the desktop client. However, its not. The issue is that on the desktop client I used to drag and drop images directly from the websites to the person I want to sent it to. Unfortunately, Franz crashes when I try to drag an image from Safari straight into Franz's Whatsapp tab of my friend.

 

### Expected Behavior

Ideally, dragging an image from Safari, it should upload the image normally.

### Current Behavior

Franz crashes on image being dragged and dropped from Safari.
However, its working normally when I drag an image that is saved on my desktop onto Whatsapp. But dragging from Safari creates the problem.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

This is extremely important for me, as sometimes I just want to send an image without saving it on my laptop. 

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by haraldox** [comment] 2018-01-25 10:31
this is a known issue, we are working on it... HTML dragging is currently buggy - might be an upstream issue in electron.

closing as Duplicate of #72 and #476

**Comment by haraldox** [comment] 2018-01-25 10:32
Duplicate of #476

**Closed by haraldox** 2018-01-25 10:31 UTC

**Comment by haraldox** [comment] 2018-01-25 10:36
@chanakyashah in the meantime refrain from dragging HTML and drag an image from the Finder or upload the image as an attachment within WhatsApp service

**Comment by pietrofxq** [comment] 2018-02-22 14:54
I`m having the same issue in ElementaryOS. When I drag a file from a folder to any app in Franz, it crashes and reloads.

**Comment by 80sguy** [comment] 2019-01-12 12:13
i still get this issue a lot, either when uploading an image or trying to download and view an image in whatsapp
