### ISSUE TITLE
Second screen disconnection issue

### ISSUE THREAD

**Issue by bex1995** [meetfranz/franz#677] opened 2018-02-12 17:41 UTC
Franz keep believing a second screen is plugged in when it's not.
### Expected Behavior
Franz open on the laptop screen or primarily screen setup in windows

### Current Behavior
Franz keep opening on the last "primarily screen" it was open on before the computer turning off

### Steps to Reproduce (for bugs)

1. Plug a second monitor in your computer
2. Make this monitor the primarily one
3. unplug it
4. try to reopen franz

### Context

Every time i need to use franz only with a my laptop after a day of work, i need to plug a monitor to retreive the window
### Your Environment

* Franz Version used: 5.0.0 beta15
* Operating System and version: Windows 10

**Comment by haraldox** [comment] 2018-02-13 13:12
Duplicate of #222

**Closed by haraldox** 2018-02-13 13:12 UTC
