### ISSUE TITLE
Back and forward keyboard shortcuts

### ISSUE THREAD

**Issue by adarshv90** [meetfranz/franz#498] opened 2017-12-22 09:11 UTC
### Feature Description
Keyboard shortcut to navigate back and forward within a service (CMD+leftArrow and CMD+rightArrow). And maybe a loading progress bar at the top

### Motivation and Context
Since some of the supported services are full blown websites (GitHub), it makes sense to have navigation support. If I click on a link and it takes me out of the website, there is no way to get back other than disabling and re-enabling the service (reloading just reloads the current page).

**Comment by BrianGilbert** [comment] 2017-12-23 21:22
Duplicate of #385

**Closed by BrianGilbert** 2017-12-23 21:22 UTC
Labels: duplicate
