### ISSUE TITLE
Not being able to add a custom icon

### ISSUE THREAD

**Issue by kassio** [meetfranz/franz#1926] opened 2020-11-17 15:27 UTC
**Describe the bug**
The custom icon field is not working. Neither clicking or dragging an image on it works

**To Reproduce**
1. Go to 'Edit service'
2. Click on 'Custom Icon field'
4. Nothing happens

**Expected behavior**

Open a file selector to select an image

**Screenshots**

<img width="161" alt="Franz" src="https://user-images.githubusercontent.com/120483/99409109-ef76dc00-28e8-11eb-9b0d-877efa09acab.png">

**Desktop (please complete the following information):**
 - OS: 
    ProductName:	macOS
    ProductVersion:	11.0.1
    BuildVersion:	20B29

**Comment by ziegenberg** [comment] 2021-01-02 11:32
Also a duplicate of #1913.

**Comment by ziegenberg** [comment] 2021-01-04 15:07
Was fixed by resolving #1951. Can be closed now.

**Closed** 2021-01-09 12:21 UTC
