### ISSUE TITLE
White page in Linux

### ISSUE THREAD

**Issue by GHostlyFOX** [meetfranz/franz#280] opened 2017-11-15 03:09 UTC
Ubuntu 16.10, Ubuntu 17.10 

After authorization in the service, only a white page is displayed until you restart the program completely.

Because of this, you can not authorize for example in Gmail, after entering the login and password, you must also enter the code from the SMS. But the SMS page is not displayed. After restarting the program, everything starts again.

**Comment by adlk** [comment] 2017-11-15 10:12
Seems likek a duplicate of #253

**Closed** 2017-11-15 11:37 UTC
