### ISSUE TITLE
Whatsapp does not open - says it needs a newer version of chrome

### ISSUE THREAD

**Issue by ifireball** [meetfranz/franz#1115] opened 2018-11-14 06:45 UTC
### Expected Behavior
Whatsapp should work

### Current Behavior
When trying to access whatsapp the following message shows up:

```
WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
```

### Possible Solution
Perhaps update the version of Electron being used internally?

### Steps to Reproduce (for bugs)
1. Setup a Whatsapp account in Franz

### Your Environment
* Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / linux / x64
  (Installed via AppImage)
* Operating System and version: RHEL 7.6 x86_64

**Comment by jgabriel98** [comment] 2018-11-14 18:33
Same problem here. but in Steps to Reproduce i didn't had to setup Whatsapp account, i just opened the Whatsapp service (wich was already setted up ) and got this error.

**Comment by mini890** [comment] 2018-11-15 14:52
Same problem occured on Windows using Version 5.0.0-beta.18.

**Comment by jomobro** [comment] 2018-11-15 21:44
Same problem on Ubuntu 18.04.1 LTS, Franz 5.0.0-beta.19

**Comment by pedrolarben** [comment] 2018-11-16 07:57
Yesterday I had same problem. It got fixed today.  Ubuntu 18.04.1 LTS.

**Comment by philcryer** [comment] 2018-11-16 14:56
> Yesterday I had same problem. It got fixed today. Ubuntu 18.04.1 LTS.

Assume you mean in master, and not in a release. Still an issue in 5.0.0-beta-18 win10, that's the latest via the site and 'releases' link here.

**Comment by ptrj** [comment] 2018-11-16 15:09
Maybe it's not a problem of Franz app. Maybe Whatsapp block or wrong parse user agent of Franz?
```
Mozilla/5.0 (Your OS HERE) AppleWebKit/537.36 (KHTML, like Gecko) Franz/5.0.0-beta.18 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36
```

**Comment by closingin** [comment] 2018-11-19 16:09
I don't have any problem on my side, weird.

**Comment by jomobro** [comment] 2018-11-20 19:32
Fixed now

**Comment by mini890** [comment] 2018-11-21 02:08
Reloading the service a few days later and no longer have any issue.

**Closed** 2018-11-21 10:10 UTC

**Comment by brunofunnie** [comment] 2018-11-30 01:41
Same here, but deleting and adding again didn't worked for me.

### Your Environment
* Franz Version used:
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
* Operating System and version:
Pop! OS (18.04 LTS) clean install just with Chrome (installed from google's deb)

**Comment by manyasone** [comment] 2018-11-30 09:41
Same problem for me, since yesterday.
I just updated from Version 4 to 5.

* Version: 5.0.0-beta.18 (installed via deb file)
Release: 1.8.4 / win32/ x64
* Operating System and version:
** Windows 10 Pro
** Version 1803
** Build 17134.407

**Comment by daren-thomas** [comment] 2018-11-30 10:20
I have the same problem. Deleting and re-adding the WhatsApp account _does_ work, but only temporarily, as in, re-starting the computer will revert back to the symptoms described above.

- Version: 5.0.0-beta.18
- Release: 1.8.4 / win32 / x64
- OS: Windows 10 Pro

**Comment by helmar74** [comment] 2018-11-30 11:18
Same problem here.
Updated to Version 5. 
Now Whatsapp isnt' working. 
Errormessage:
```
WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
```

**Comment by DjMcBee** [comment] 2018-11-30 12:38
Same problem - but removal of service, turn off application and add whatsapp service again solve my problem (did not work only removal and adding again - have to turn it off).
* Version: 4.0.4 (build 40)
* Release: 1.3.1 / win32 / x64
* OS: Windows 10 Pro (10.0.17134 Build 17134)

BTW: Seems like there is no active development for last few months? :-)

**Comment by closingin** [comment] 2018-11-30 12:49
Hello @DjMcBee , the development went quiet because Stefan got sick, things are going back to normal, but there's a lot of issues to take care of now :slightly_smiling_face:

**Comment by manyasone** [comment] 2018-11-30 12:54
> Same problem - but removal of service, turn off application and add whatsapp service again solve my problem (did not work only removal and adding again - have to turn it off).

Removing whatsapp, uninstalling and reinstalling franz, adding whatsapp again did not solve the issue.

Removing whatsapp once more and adding it again did the trick for some reason - but only until restarting franz. Then, the same problem occured again.

**Comment by DjMcBee** [comment] 2018-11-30 13:15
> Hello @DjMcBee , the development went quiet because Stefan got sick, things are going back to normal, but there's a lot of issues to take care of now 🙂

Hello @closingin, thanks for the information - glad to hear that. Anyways i appreciate your work a lot guys ...

**Comment by gitanoqevaporelmundoentero** [comment] 2018-11-30 17:34
Same problem here. I've got it fixed on my Ubuntu 18.04 installation with Franz Version: 5.0.0-beta.18 (Release: 1.8.4 / linux / x64) simply by right-clicking on WhatsApp service icon and selecting "reload".

**Comment by Wouter0100** [comment] 2018-11-30 18:43
Seems to be a permanent issue now.

**Comment by valentinconesa** [comment] 2018-11-30 20:33
Same problem here with Ubuntu 16.04. It works reloading whatsapp service.

**Comment by ivorafael** [comment] 2018-11-30 20:37
Same problem here.

Franz Version 5.0.0-beta.18 (5.0.0-beta.18.903)
MacOS Mojave Version 10.14.1 (18B75)

**Comment by ecavalcanti** [comment] 2018-12-01 00:40
+1

**Comment by ergelo** [comment] 2018-12-01 07:36
+1. I updated Franz today and it worked briefly. Tonight it show the same error again.

**Comment by jbiskofski** [comment] 2018-12-02 01:41
Same issue. On Mac

**Comment by trashtatur** [comment] 2018-12-02 16:59
Same issue in Windows 10 and Archlinux. Tested that on 3 devices now. Sometimes reloading the service fixes it for one session, but thats all.

**Comment by peerberberich** [comment] 2018-12-02 19:53
Same Issue:
Ubuntu 18.04.1 LTS

**Comment by karanbajaj23** [comment] 2018-12-03 04:51
Same issue - "WhatsApp works with Google Chrome 36+"
Same observation - On removing and re-adding WhatsApp service, it works. Upon restart, same error shows up.

Disable/Enable service - No effect.
Reload service - No effect.

Removing, adding and authenticating service is a pain. Considering how much of Franz tends to be WhatsApp, guess we got to solve this soon.

**Comment by Noam-greenberrg** [comment] 2018-12-03 07:14
Same issue  
 "WhatsApp works with Google Chrome 36+"

**Comment by masbog** [comment] 2018-12-03 07:56
> Same problem here :
> 
> Ubuntu 18.04
> Version: 5.0.0-beta.18
> Release: 1.8.4 / linux / x64
> 
> I delete and add again the whatsapp service and everything works fine now.

not work for me on MacOSX :(

**Comment by shar1z** [comment] 2018-12-03 08:48
+1
MacOS 10.13.6 (HS)

**Comment by juliann** [comment] 2018-12-03 10:37
+1
win 10 Pro 17763.134 Version 1809

**Comment by reginastracii** [comment] 2018-12-03 11:11
+1 Ubuntu 18.10 and Mojave 10.14.1

**Comment by nunesdev** [comment] 2018-12-03 13:08
+1 Mojave 10.14

**Comment by laerteg** [comment] 2018-12-03 19:07
few minutes ago I installed alternative tool called Rumbox and the same behavior, when I added the whatsapp service the same message related to chrome update.

**Comment by NikolaiSzabados** [comment] 2018-12-03 19:47
+1 Win 10 Pro

**Comment by derrenbrown** [comment] 2018-12-06 11:10
This issue is really a bug in WhatsApp web client. Wouldn't it be more direct if we - the victims - request WhatsApp to fix it?

I did that by clicking on "Web and Desktop" at this page:
https://www.whatsapp.com/contact/?subject=messenger

**Comment by pichirichi** [comment] 2018-12-10 08:11
> Hello, as announced [here](https://meetfranz.com/support/), the problem is being investigated and a fix will surely come soon. You don't need to confirm the bug anymore, we're all aware of this 😉

The suggested workaround in the post is not working.

**Comment by adlk** [comment] 2018-12-10 08:40
Please try to disable/enable WhatsApp if this error appears. Does this help?

**Comment by Wouter0100** [comment] 2018-12-10 08:41
@adlk unfortunately not :(

**Comment by adlk** [comment] 2018-12-10 13:33
😞 
As far as I know, it's an issue with WhatsApps service worker. I seems that a new approach is necessary.

**Comment by jbiskofski** [comment] 2018-12-10 14:55
For what its worth, 

As a temporary solution I installed Franz v4, and WhatsApp works correctly there. So however v4 handles the service still works.

**Comment by pluralism** [comment] 2018-12-11 14:59
Currently I'm using Fiddler as a workaround. You can add the following code to the end of **OnBeforeRequest** method:

```C#
if(oSession.HostnameIs("web.whatsapp.com")) {
    oSession.oRequest["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36";
}
```

You only need to use Fiddler while logging in. Once you're logged in, whatsapp will work even without Fiddler.

**Comment by bvrulez** [comment] 2018-12-14 13:33
I have the same problem of a Laptop using Win 10 and Franz 4.0.4. Deleting and re-adding does not solve the issue. On my PC with Win 10 Franz works fine.

**Comment by adlk** [comment] 2018-12-14 13:55
Locking in favor of #1185
