### ISSUE TITLE
in macOS after computer sleeps and wakes up application active service screen shows empty

### ISSUE THREAD

**Issue by miguelperez** [meetfranz/franz#589] opened 2018-01-17 16:05 UTC
Usually before taking a break, I will put the computer to sleep. Clicking on the sleep menu item under de apple logo.

Once I come back and login into the computer franz window is white. Only the services logos are shown, but their content disappeared. I need to then right click on the logo and hit Reload service.

### Expected Behavior

1. Open Franz
2. Do some work
3. Put the computer to sleep
4. After the computer requires your password to login, login back
5. Check the franz window and the services should be showing their last shown screen.

### Current Behavior

1. Open Franz
2. Do some work
3. Put the computer to sleep
4. After the computer requires your password to login, login back
5. Check the franz window and all active services show a blank screen

### Screenshots (if appropriate):
![screen shot 2018-01-17 at 10 55 39 am](https://user-images.githubusercontent.com/141042/35052611-051f0634-fb76-11e7-910e-4ff9bb016171.png)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: Version 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: macOS High Sierra 10.13.2 (17C88)

**Comment by haraldox** [comment] 2018-01-18 09:51
Duplicate of #594

**Closed by haraldox** 2018-01-18 09:51 UTC
