### ISSUE TITLE
Ability to place all services at the top.

### ISSUE THREAD

**Issue by ysb33r** [meetfranz/franz#428] opened 2017-12-08 12:42 UTC
In the older versions, the services were all listed in the top. The new beta versions have them on the sidebar, which becomes painful to navigate when  one has a lot of services.

![prent](https://user-images.githubusercontent.com/907624/33766396-1d5faf94-dc15-11e7-9ad9-0c64cdc39321.png)

### Possible Solution

. Have the ability to configure the bar to be on the left or the top
. Option disable scrolling by but rather overflow to more rows (or columns)

### Your Environment
* Franz Version used: 5.0.0-beta.14
* Operating System and version: Mac El Capitan

**Comment by adlk** [comment] 2017-12-08 15:36
Duplicate of #156

**Closed by adlk** 2017-12-08 15:36 UTC
