### ISSUE TITLE
Memory comsumption and process opened

### ISSUE THREAD

**Issue by seiferflo** [meetfranz/franz#15] opened 2017-10-18 11:07 UTC
I'm trying to understand why Franz needs to open so many processes in Windows to run and why do they consume so much memory? 
Attached is a screenshot of my configuration for 5 services used.

### Expected Behavior
6 processes open at the max. 1 for Franz and 1 per service would make sense

### Current Behavior
18 processes opened. 13 of them used by Franz, 1 per service x 5

### Screenshots (if appropriate):
![2017-10-18 12-49-30_windows task manager](https://user-images.githubusercontent.com/10022442/31715483-60faa60c-b404-11e7-9217-2318f464f903.gif)

### Steps to Reproduce (for bugs)
Just open Franz and look at the task Manager in Windows.

### Your Environment
* Windows 7 Pro x64
* Franz Version used: 5.0b10

**Comment by adlk** [comment] 2017-10-18 11:51
Thanks for reporting this. I need to do some research and testing. Please stay tuned.

**Comment by hsiktas** [comment] 2017-12-26 16:41
No idea if it is helpful but Slack's 3.0 beta managed to reduce their RAM usage by a huge amount. Here is their write-up: https://slack.engineering/growing-pains-migrating-slacks-desktop-app-to-browserview-2759690d9c7b

**Comment by durbanpoison** [comment] 2018-01-04 04:41
I came here to also report memory usage issues on Linux Mint. The app is unfortunately nearly unusable with just 6 services connected, and I am hoping to connect many more (I participate in many open source online communities).  

In my normal browser usage, I use the app Tab Suspender to keep my memory usage manageable. I am hoping the Franz developers can implement a similar feature that allows me to choose which services are "active" and thus consuming system resources.  

https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/

(Sorry if this is hijacking the issue, I hope the above suggestion can be a solution for OP's issue as well as mine.)

**Comment by haraldox** [comment] 2018-01-13 08:59
we're still looking into this! don't worry, we want Franz to be as lean as possible :)

**Comment by haraldox** [comment] 2018-01-13 12:51
duplicate of https://github.com/meetfranz/franz/issues/265

**Closed by haraldox** 2018-01-13 12:51 UTC
Labels: research necessary

**Comment by bigtunacan** [comment] 2018-07-03 15:46
Just came to chime in with the same issue.  Just using Discord and a couple of Slacks on Mac OS X El Capitan and Franz is consuming more than 2GB of RAM.

**Comment by hannojg** [comment] 2019-01-04 14:02
I am facing the same issue. I have 20 GB RAM installed. Lately, Franz starts sometimes a rampage and take around 12-16 GB which leads to an almost freezing PC.
I love this tool so much that I even bought the premium support, but this is really annoying. Would be great to have something like a RAM management setting, so it can't get insane 😋

**Comment by mP765** [comment] 2019-06-10 20:20
@adlk Are you going to fix this at any time? As far as I can see, all tickets regarding this (quite severe) issue are closed.
Many of my colleagues already quit using Franz and if the memory consumption stays that extreme, I will have to quit as well. 
1.5GB RAM is way too much for Whatsapp, Telegram and 3x Slack and slows down the PC noticeably.

**Comment by TomasSestak** [comment] 2019-06-11 20:53
i have slack and fb and there are like 4 proccesses totalling 1500mb, insane

**Comment by bigtunacan** [comment] 2019-06-11 21:43
Clearly they either don't care to fix this issue, or they don't have the ability to do so.  I for one quit using this.

**Comment by okevino47** [comment] 2019-11-14 06:56
![image](https://user-images.githubusercontent.com/35851082/68833501-f330bb00-06f6-11ea-8e45-bc918f605044.png)

with 13 services activated i have near 23 processes used by Franz...
This post started 2 years ago, maybe it's time to talk less and act more maybe ?
Is that possible to fix this HUGE problem or not ?
