### ISSUE TITLE
Many Franz services. High memory consumption

### ISSUE THREAD

**Issue by Rafaal911** [meetfranz/franz#459] opened 2017-12-13 13:14 UTC
Is possible to reduce the memory consumption of Franz in a next release? Now I am using 4 services (WhatsApp, Twitter and 2 slack workspaces) and checking on my activity monitor I see that Franz alone takes around 1GB from my memory. That is a lot!
And why are there so many Franz Helper?

Thanks!
<img width="804" alt="screen shot 2017-12-13 at 10 13 16" src="https://user-images.githubusercontent.com/16694630/33940596-5173b8ca-dfee-11e7-84f2-c661e7ae0da9.png">

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: MacOS High Sierra 10.13.1

**Comment by adlk** [comment] 2017-12-13 13:18
Duplicate of #265

**Closed by adlk** 2017-12-13 13:18 UTC
