### ISSUE TITLE
Franz window does not appear on display

### ISSUE THREAD

**Issue by masenka76** [meetfranz/franz#351] opened 2017-11-27 09:18 UTC
### Expected Behavior
To see the Franz window on my display as it was few days ago.

### Current Behavior
The Franz window is out of the displays' borders and I can't see it.
It flashes in a moment when I choose Franz icon on Taskbar and desapears in the  right border of the second display

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment] 2017-11-27 10:08
Duplicate of #222

**Closed by adlk** 2017-11-27 10:08 UTC
