### ISSUE TITLE
No Windows Notifications since Franz 5

### ISSUE THREAD

**Issue by LValerius** [meetfranz/franz#282] opened 2017-11-15 11:03 UTC
Since Franz 5, I do not receive any more windows system notifications when receiving e.g. new messeges in whatsapp. Franz itself show the notifications, as always, through red dots, but the windows system notification is missing. I also reinstalled the program but it remains the same. Any ideas?

Windows 10 Version 1709 (Fall Creators Update)
Franz 5, beta 13

I did not change anything but upgrading Franz to version 5.

Thanks a lot! Keep up the good work!

EDIT: Currently used services:
- WhatsApp
- Slack
- Google Keep
- Google Calendar
- Toggl
- Office 365 Outlook

**Comment by adlk** [comment] 2017-11-15 11:31
Duplicate of #173 

@LValerius You can get more information and updates in the linked issue.

**Closed by adlk** 2017-11-15 11:31 UTC
