### ISSUE TITLE
CANT DISABLE Notifications on MAC 

### ISSUE THREAD

**Issue by dwightee** [meetfranz/franz#290] opened 2017-11-16 20:39 UTC
Hi guys this bug is in franz ever since I can remember you cant mute notifications. I would love to have an option to just dial down the volume. It is insanely loud and supper annoying, whenever franz doesnt have the focus it beeps. Disable notifications does not work.

(this might be only for whatsapp I have not noticed it with other services, but its probably because whatsapp has this idiotic beepish sound, whereas fb and slack are low volume sounds)

Thank you, for your time, your app is awesome !

**Comment by adlk** [comment] 2017-11-17 08:20
This is kind of an duplicate of #8 and was fixed in #252

This will be shipped soon.

**Closed by adlk** 2017-11-17 08:20 UTC
