### ISSUE TITLE
Drop images to Whatsapp and Facebook Messenger don't work and Crashes the service.

### ISSUE THREAD

**Issue by Kasukisan** [meetfranz/franz#476] opened 2017-12-15 16:31 UTC
![image](https://user-images.githubusercontent.com/34579675/34051102-4e7e25da-e18b-11e7-8795-67b6ce08778c.png)

**Comment by adlk** [comment] 2017-12-20 14:24
Duplicate of #72

**Closed by adlk** 2017-12-20 14:24 UTC

**Comment by BigFunkyMan** [comment] 2018-02-26 08:26
Hallo,
on my PC are the same Problems!
if i drop & Paste a picture in WhatsApp of Facebock franz crashed :(
