### ISSUE TITLE
Launch Franz on Start not working on MacOS High Sierra

### ISSUE THREAD

**Issue by SergioSGil** [meetfranz/franz#79] opened 2017-10-23 15:08 UTC
When I activate the function of NO OPEN FRANZ in the login of my laptop, if I log off and login again, Franz opens.

### Expected Behavior
When I activate the function of NO OPEN FRANZ in the login of my laptop, if I log off and login again, Franz opens.

### Current Behavior
This basic function should work properly.

### Screenshots:
https://imgur.com/a/yStLb

### Possible Solution
This basic function should work properly.

### Steps to Reproduce (for bugs)

1. Open Franz
2. Go to settings --> general
3. Disable Launch franz on start 

### Your Environment

* Franz Version used:  Versión 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: Macos High Sierra (Macbook Pro 2013)

**Comment by adlk** [comment] 2017-10-23 18:59
Duplicate of #17

**Closed by adlk** 2017-10-23 18:59 UTC
