### ISSUE TITLE
Badge always showing in Slack service

### ISSUE THREAD

**Issue by thewinger** [meetfranz/franz#21] opened 2017-10-19 07:12 UTC
### Expected Behavior

If there is no unread message in slack, icon shouldn't show a badge.

### Current Behavior

Slack service shows a badge even though when I enter there are no unread messages.

### Screenshots (if appropriate):
<img width="287" alt="screen shot 2017-10-19 at 09 10 09" src="https://user-images.githubusercontent.com/121455/31758390-94ea14da-b4ad-11e7-9434-e11ca3b4c024.png">

### Context

It's annoying

### Your Environment

* Franz Version used: 5.0.0-beta.10
* Operating System and version: macOS High Sierra 10.13

**Comment by adlk** [comment] 2017-10-19 08:30
Duplicate of meetfranz/recipe-slack#1

This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
www.github.com/meetfranz/recipe-slack

**Closed by adlk** 2017-10-19 08:30 UTC
