### ISSUE TITLE
Left Nav covers takes up a ton of real estate. Add ability to move to top nav or hide side nav

### ISSUE THREAD

**Issue by yagrossman** [meetfranz/franz#256] opened 2017-11-10 16:23 UTC
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment] 2017-11-10 16:32
Duplicate of #156

**Closed by adlk** 2017-11-10 16:32 UTC
