### ISSUE TITLE
Add a dark mode or theming

### ISSUE THREAD

**Issue by ProfessorLogout** [meetfranz/franz#551] opened 2018-01-09 18:08 UTC
### Feature Description
A dark-mode like many applications (e.g Discord, IntelliJ and others) offer or the possibility to create and install own themes to manipulate the look of Franz.

### Motivation and Context
The proposed dark-mode is a feature many users got accustomed to in other applications and that can benefit users working in dark environments.

### Expected Behavior
A slider in the settings to enable dark-mode permanently.
Additionally a time-based activation could also co-exist there.

### Current Behavior
Currently no change of the theming of the application is possible

### Your Environment
* Franz Version used: 5.0.0-beta.14
* Operating System and version: Kubuntu 16.04 (Main Computer) and Windows 7 and 10 on various other machines.

**Comment by colinodell** [comment] 2018-01-09 22:29
Duplicate of #49?

**Closed** 2018-01-10 09:26 UTC

**Comment by adlk** [comment] 2018-01-10 09:27
There is already a proposed PR for that (#362) that needs to be finished.

**Comment by ssulistyo** [comment] 2019-06-30 10:22
Can the Franz dark mode be connected to Mac OS X dark mode? https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface
