### ISSUE TITLE
Open external links in new browser window

### ISSUE THREAD

**Issue by koma-private** [meetfranz/franz#244] opened 2017-11-09 07:23 UTC
Hi. I would appreciate hearing your opinion on this. I like Franz for it's simple design but sometimes I have to restart Franz to reset services when they loaded external links in the same window and I want to go back to their "serviceURL".

So, I'm now studying to fix this issue by making index.js scan for external links and preventing Franz to load them. Is it suitable for recipes to do such pre-process?

### Expected Behavior
Always open external links in a new window

### Possible Solution
For recipe-side, avoid loading such links in Franz as follows :
```javascript
module.exports = Franz => class SomeService extends Franz {
    events = {
        'dom-ready': '_scanForExternalLinks',
    }

    _scanForExternalLinks(event) {
        [].forEach.call(document.querySelectorAll("a"),
            e => {
                if (e.host !== window.location.host)
                    e.setAttribute("onclick", "window.open(this.href); return false;");
            })
    }
};
```
Or, for client-side, I think there are some options :
1. Force always open external links in other browser window
2. Load serviceURL when invoked by "reset service" menu
3. As long as it does not spoil the current Franz design, add "home" button somewhere

**Comment by eddowding** [comment] 2017-11-14 13:25
Related: when I open links from gmail they open a new chrome window, but don't load the URL

**Comment by batmel** [comment] 2017-11-17 10:01
For me it's not only Gmail, but all the other applications (Telegram, Whatsapp ..) as well. As soon as I click on a link, a new chrome window will be opened, but it does not load the URL.

**Comment by koma-private** [comment] 2017-11-18 05:43
I may have found a cause of the new browser window problem.

When I was debugging my Teamwork Projects recipe, I noticed a strange behavior of a print button located at gantt chart page. This button usually opens a new window showing a "Generating printable document..." message untll printing data is ready, then opens a print dialog of system when I use Teamwork Projects with other browsers.

But with Franz, it just opens a blank window and I cannot proceed to print out dialog. Teamwork Projects opens a new window by calling `window.open` function as follows:

```
this.printWindow = window.open("", "", "width=" + window.innerWidth + ",height=" + window.innerHeight),
this.printWindow.document.write('<html><body style="margin: 0;">Generating printable document&hellip;</body></html>'),
this.printWindow.document.close(),
```

But when the `window.open` function is called inside a WebView, it just returns a [BrowserWindowProxy](https://github.com/electron/electron/blob/master/docs/api/browser-window-proxy.md)
to `this.printWindow` variable. And invoking `this.printWindow.document.write` will fail because `BrowserWindowProxy` provides limited functionality and `this.printWindow.document` object is undefined.

Fortunately, electron provides also Chrome's built-in `window.open()` implementation as described [here](https://github.com/electron/electron/blob/master/docs/api/window-open.md), so regarding the recipe of Teamwork Projects it fixes the problems by adding a property of `webpreferences="nativeWindowOpen=yes"` to the `WebView` tag defined at  /src/components/services/content/ServiceWebview.js

Hope other services like Gmail, Telegram and Whatsapp will also be fixed by this solution.

**Comment by adlk** [comment] 2017-11-18 20:12
As you've written correctly in your PR this has the side effect open opening every link with a `target="_blank"` in Franz and in the browser. Unfortunately I don't have a solution yet.

**Comment by haraldox** [comment] 2018-01-15 12:11
possible Duplicate of #264

**Closed by haraldox** 2018-01-15 12:11 UTC
Labels: links [temp]

**Comment by koma-private** [comment] 2018-01-15 12:37
@haraldox
Although I think I should change the title of this issue, I’m talking about some services which have to open a new window and change the content of  it automatically by Javascript, here. So your proposal method “right click” doesn’t work.

As for services which won’t work in normal Franz, I applied a small patch described in https://github.com/meetfranz/franz/issues/298 by myself

**Comment by koma-private** [comment] 2018-01-15 13:06
@adlk
Hi. This is the one of troublesome issues, about that some services need the nativeWindowOpen property in WebView tag to work normally. 
I appreciate it if this hack can be activated by some option like “useNativeWindowOpen=true” in the package.json per service because this change has side effects as you know, and I think it’s difficult to modify the current behavior of Franz. What do you think?

P.S. Sorry, I closed https://github.com/meetfranz/franz/pull/298 by my noob mistake, force push :(
