### ISSUE TITLE
Dark Theme for Tab Bar

### ISSUE THREAD

**Issue by kristofm** [meetfranz/franz#339] opened 2017-11-24 08:35 UTC
The current bar has a white-silverish color which does not fit well at all with things like discord (which has a complete dark theme) or other desktop applications.

This is a very basic feature that has a very big impact. Youtube (and many other big services) introduced their dark theme after they realized that a huge amount of people were using third party scripts to modify the basic youtube layout. (Almost all of them on userstyles.org are the dark theme ones)

This is not a recommendation to change the layout itself, it is **just to change / give an option to select between a darker color for the tab bar.**

For me it is very bothersome to have to deal with the white/greyish color of the tab bar which now is also on the left hand side which can interfere with gaming quite a bit. (The old 4.0.4 version had it on the top so the issue was not as noticeable in my opinion.)

**Comment by adlk** [comment] 2017-11-24 08:36
Duplicate of #49

**Closed by adlk** 2017-11-24 08:36 UTC
