### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by Vaibhav** [meetfranz/franz#734] opened 2018-02-26 21:35 UTC
### Expected Behavior

Dark Theme would change the side bar, settings and add a new service menus to darker colour. A lot of websites let users have the option for having light or dark theme, could be a good addition to Franz app. 

This would help match other services of mine that are running in a dark theme mode, (ex. HipChat).

**Comment by haraldox** [comment] 2018-02-28 13:57
Duplicate of #49

**Closed by haraldox** 2018-02-28 13:57 UTC
