### ISSUE TITLE
So my spell checker "acts" like it's a premium feature

### ISSUE THREAD

**Issue by Gaboris** [meetfranz/franz#1165] opened 2018-12-09 14:37 UTC
So this is really weird. I went into my settings to look for an update again and I noticed that the spellchecker out of nowhere got a great big blue outline, is disabled and has a blue button telling me to switch to premium.

I'm pretty sure this wasn't the case the last time I tried updating so is this a REALLY weird bug or were we REALLY not told about this change happening even without updating?

**Comment by adlk** [comment] 2018-12-09 20:16
The issue is now fixed (it was an issue with the features API)
Please just reload/restart Franz and you should be good to go!

**Closed by adlk** 2018-12-09 20:16 UTC
