### ISSUE TITLE
Settings toggles not working.

### ISSUE THREAD

**Issue by bakman2** [meetfranz/franz#671] opened 2018-02-09 17:04 UTC
In Settings I am not able to disable : 
- Keep Franz in background when closing the window
- Show Franz in system tray
- Display disabled services tabs
- Show unread message badge 
- Enable spell checking

Responding checkboxes: 
- Launch Franz on start
- Include beta versions

### Expected Behavior
Click should disable checkbox.

### Current Behavior
Checkbox animation showing a little movement, jumps back and are not disabling the options.
 
### Your Environment
* Franz Version used:5.0.0-beta.15.607
* Operating System and version: MacOS 10.13.3 (17D47)

**Comment by Stanzilla** [comment] 2018-02-12 15:22
Can confirm, not working on Windows 10 either.

**Comment by haraldox** [comment] 2018-02-13 14:04
Duplicate of #615

**Closed by haraldox** 2018-02-13 14:04 UTC
