### ISSUE TITLE
Slack update: "Please update your third-party app or use the Slack desktop app"

### ISSUE THREAD

**Issue by aipi** [meetfranz/franz#1347] opened 2019-03-20 14:25 UTC
**Describe the bug**
Slack request to update its app.

**Screenshots**
![image](https://user-images.githubusercontent.com/17441599/54691730-87b03280-4b02-11e9-9dab-20fbc3a54813.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by nikitira** [comment] 2019-03-20 15:31
Also since ~3 weeks on Mac Mojave 10.14.3

**Comment by TheCedarPrince** [comment] 2019-03-21 00:47
**Describe the bug:**

I am having the same issue; I was able to log into the Slack app through Franz earlier today but am now unable to access Slack through Franz.

**Screenshots:**

![image](https://user-images.githubusercontent.com/29561456/54727917-f4eab480-4b50-11e9-81ba-91aadd60ec88.png)

**Desktop:** 

OS: Ubuntu 16.04

**Steps to Reproduce Bug:**

1) Open Franz
2) Attempt to open Slack through Franz

**Comment by larkin-nz** [comment] 2019-03-21 04:02
I have also tried overriding the User Agent and also having no luck!

**Comment by TheCedarPrince** [comment] 2019-03-21 05:02
Hey @larkin-nz I went with the Manual workaround method since updating Ubuntu did not seem to update Franz. Everything is operational again. 

I think we can effectively close this issue now - especially if it is simply a bug that can be fixed by a version update. Thanks again! 

Keep up the great work Franz team @aipi

**Comment by larkin-nz** [comment] 2019-03-21 05:25
Glad that worked for you @TheCedarPrince 

I agree that this should be closed now!

**Comment by aipi** [comment] 2019-03-21 14:46
@larkin-nz solution worked. Thank you so much! :heart:

**Comment by belthaZornv** [comment] 2019-03-22 07:33
> ~/home/.config/Franz/recipes/slack

`~` already indicates `home`. - `~/.config/Franz/recipes/slack` :+1: thanks for the fix bud.

**Comment by larkin-nz** [comment] 2019-03-22 07:51
@belthaZornv - Yes, it does - typo there - thanks for pointing that out! :)

**Comment by adlk** [comment] 2019-03-25 08:16
With Franz 5.0.0 (stable) or 5.0.1-beta.1 this is already fixed as we've updated to Chrome 69. 
Ad auto update. We're currently doing tests the AppImage updater in 5.0.1

**Closed by adlk** 2019-03-25 08:16 UTC

**Comment by bachi76** [comment] 2019-11-12 09:04
just fyi, that just happened again today, the method mentioned works fine (with the latest chrome version added)

**Comment by samhk222** [comment] 2019-11-18 12:50
> just fyi, that just happened again today, the method mentioned works fine (with the latest chrome version added)

Yep, i had to change to 78.0.3904.97

**Comment by testacode** [comment] 2020-05-18 15:47
Installed Franz 5.0 today, slack is not working for me. https://recordit.co/O7UUf3ofte
