### ISSUE TITLE
Customize Icons on Lefthand Side (to help sort different GMail Accounts)

### ISSUE THREAD

**Issue by corroc** [meetfranz/franz#491] opened 2017-12-20 14:43 UTC
Feature Request:

It's awesome that you can add multiple versions of the same service under different accounts, like GMail. I have 3 GMail accounts added, and all icons are the same. If I could change icons (either from a repository of icons, or ability to upload one myself), then I could be visually reminded of which icon is for which account.

Cheers!

**Comment by adlk** [comment] 2017-12-21 11:12
Duplicate of #291

**Closed by adlk** 2017-12-21 11:12 UTC
