### ISSUE TITLE
Icon in menubar

### ISSUE THREAD

**Issue by mvc3131** [meetfranz/franz#82] opened 2017-10-23 16:43 UTC
The icon in the menubar is not visible

### Expected Behavior
The icons in the menu bar are generally white, with a red dot for indicating notifications. 

### Current Behavior
The icon itself is in a dark color that it is not visible. Only the notification indicator is visible in normal state. Its good in the selected state. (Attached screenshots for reference)

### Screenshots (if appropriate):
<img width="626" alt="screen shot 2017-10-23 at 10 07 58 pm" src="https://user-images.githubusercontent.com/13113716/31901504-3b2e9246-b83f-11e7-8854-bd05d25d03e9.png">

<img width="591" alt="screen shot 2017-10-23 at 10 09 00 pm" src="https://user-images.githubusercontent.com/13113716/31901565-6a975022-b83f-11e7-9b9a-9f18b8bc6b7b.png">

### Your Environment
Macbook Pro - 15" Retina.
Franz-5.0.0-beta.10
macOS Sierra
Version: 10.12.6

**Comment by adlk** [comment] 2017-10-23 18:58
Duplicate of #1

**Closed by adlk** 2017-10-23 18:58 UTC
