### ISSUE TITLE
Franz not showing Notification Badge for Whatsapp.............

### ISSUE THREAD

**Issue by faunaman** [meetfranz/franz#1995] opened 2021-03-01 17:56 UTC
**Describe the bug**

I have WhatsApp service. I do not get notification badges from new Whatsapp messages in Franz app in Mac app bar. It only happens with two Whatsapp services, notifications work fine with Skype and Telegram

**Expected behavior**
When I receive a new message I would like to see some indicator from it.

**Desktop (please complete the following information):**

Catalina 10.15.7, Franz 5.6.1 (5.6.1.1830)

**Comment by jasmines** [comment] 2021-03-02 12:07
Same here, Ubuntu 20.10, Franz 5.6.1
The problem is that Whatsapp window is no more opening full width, but it's fixed in a certain width (see the difference with Telegram, as example). When this happens, notifications don't work.
Once I was able to solve with a refresh of the service, and this used to work, as the window was going to full width after such operation, and the notifications started working again.

By now (I can't say when it started or upon what circumstances) the refresh workaround is no longer working.

**Comment by JCKodel** [comment] 2021-03-03 09:32
Every Whatsapp update generates the same issue.

Why don't you open source the services scripts (since their source are available anyway at the install location), so the community can fix notifications faster?

Then, I think GitHub is capable of build and distribute those scripts to CDNs, so Franz client just checks the CDN for new versions and updates those scripts automatically, without having to update Franz itself.

I think that way we could be more agile to service's changes.

**Comment by JAicewizard** [comment] 2021-03-03 12:04
no pelase do not do that, dont download scripts from the interwebs and run them with full user privileges thats not OK.

If this has to do with whatsapp web updates, whats causing it with this release specifically? I usually don't have this problem after whatsapp web updates, this is the first time.

**Comment by JCKodel** [comment] 2021-03-03 12:16
> no pelase do not do that, dont download scripts from the interwebs and run them with full user privileges thats not OK.
> 

Since when Franz runs scripts with "full user privileges"???
Services scripts runs in a browser context (you wouldn't even have disk access).

And opensource is safer than closed source. *I'm not telling Franz do that*, but there is no guarantee that those scripts don't send your data anyway to them (besides that, people already use Whatsapp, GMail and Telegram, knowing they WILL read and sell your messages)

> If this has to do with whatsapp web updates, whats causing it with this release specifically? I usually don't have this problem after whatsapp web updates, this is the first time.
>

Just because YOU don't have a problem, it doesn't mean everybody doesn't have it.
For me, notifications stops working from time to time (every month or so).

**Comment by JCKodel** [comment] 2021-03-03 13:25
1) Recipes are already open-sourced.

2) I rewrote the Whatsapp recipe, so it can identify the badges even if Whatsapp class names changes (it's not 100% perfect, but is close enough).

That's the pull request: https://github.com/meetfranz/recipe-whatsapp/pull/17

@JAicewizard And that's how open source works. Feel free to read my code to be sure I'm not stealing any of your precious "user privileges" ¬¬

**Comment by JAicewizard** [comment] 2021-03-03 13:37
I know how open source works, why are you being so aggressive??
I think changing the recipe is better then dynamically downloading scripts without the users permission.

**Comment by Marniac95** [comment] 2021-03-04 11:57
Sorry for my ignorance but I'm a bit slow on these things. Does any of this mean that there's a way to fix the issue? It's really annoying not having the notification badge appear.

**Comment by JCKodel** [comment] 2021-03-04 12:06
> Sorry for my ignorance but I'm a bit slow on these things. Does any of this mean that there's a way to fix the issue? It's really annoying not having the notification badge appear.

Yes. This is a contribution to fix this problem now and in the future.

Now, it depends on Franz developers to check my solution and integrate it on a new Franz version (or they can simply ignore it - is their choice).

If you are in a hurry, you can copy and paste the code from this PR using this link: https://raw.githubusercontent.com/meetfranz/recipe-whatsapp/77a70a4f738f15ab542ec8685a6d161e60a8f4b2/webview.js

Then, you need to find the WhatsApp recipe in your machine (for Windows, it is located in `%USERPROFILE%\AppData\Roaming\Franz\recipes\whatsapp` (or C:\Users\YourPersonalFolderNameHerre\AppData\Roaming\Franz\recipes\whatsapp). I don't have a Mac or Linux machine right now, so, if it is your case, maybe someone else can help you finding the file.

In that folder, there is a file named `webview.js`. Open it with a text editor (Notepad, for instance), than delete all and paste the contents of the above link.

Then, you only need to restart Franz (or reload the Whatsapp service).

**Comment by Marniac95** [comment] 2021-03-04 21:02
> > Sorry for my ignorance but I'm a bit slow on these things. Does any of this mean that there's a way to fix the issue? It's really annoying not having the notification badge appear.
> 
> Yes. This is a contribution to fix this problem now and in the future.
> 
> Now, it depends on Franz developers to check my solution and integrate it on a new Franz version (or they can simply ignore it - is their choice).
> 
> If you are in a hurry, you can copy and paste the code from this PR using this link: https://raw.githubusercontent.com/meetfranz/recipe-whatsapp/77a70a4f738f15ab542ec8685a6d161e60a8f4b2/webview.js
> 
> Then, you need to find the WhatsApp recipe in your machine (for Windows, it is located in `%USERPROFILE%\AppData\Roaming\Franz\recipes\whatsapp` (or C:\Users\YourPersonalFolderNameHerre\AppData\Roaming\Franz\recipes\whatsapp). I don't have a Mac or Linux machine right now, so, if it is your case, maybe someone else can help you finding the file.
> 
> In that folder, there is a file named `webview.js`. Open it with a text editor (Notepad, for instance), then delete all and paste the contents of the link above.
> 
> Then, you only need to restart Franz (or reload the Whatsapp service).

Hi! Thank you so much for the reply. It really helped!

However, I find that this is only a partial fix, right? This is for a couple of reasons:

- The Whatsapp app still doesn't fit the whole window, as it did. I find this mostly uninportant, but wanted to point it out.
- The other issue I find, or more like a difference in regards of how it used to work, is that instead of getting a notification badge for each "new chat", I get one for each "new message". So, if I have 40 new messages on 3 different chats/groups, the badge will show "40", when before it showed "3".

Still, this isn't a huge deal and your fix worked wonders to help me while we wait for the devs for actually patch it up. Thanks again!

**Comment by JCKodel** [comment] 2021-03-04 21:24
> The Whatsapp app still doesn't fit the whole window, as it did. I find this mostly uninportant, but wanted to point it out.
>

Whatsapp changed its design. There is no bug to fix. This is the way Whatsapp Web is now. I don't think Franz should change anything (just passively read the unread badge count).

> The other issue I find, or more like a difference in regards of how it used to work, is that instead of getting a notification badge for each "new chat", I get one for each "new message". So, if I have 40 new messages on 3 different chats/groups, the badge will show "40", when before it showed "3".
>

The old method just checked the badge, ignoring how much unread message there was. IMO, the notification should display the number of unread messages, not threads.

Anyway, you can have the old behavior changing this part of the code:

```js
if (span.ariaLabel == "") {
  count++;
  console.log("One item found as marked as unread. Count so far = " + count);
} else {
  const unreadCount = parseInt(span.ariaLabel) || 0;

  if (span.ariaLabel.split(" ")[0] == unreadCount.toString()) {
    count += unreadCount;
    console.log("One item found as unread with counter. Count so far = " + count);
  }
}
```

delete all those lines and change them to:

```js
count += unreadCount;
```

**Comment by JCKodel** [comment] 2021-03-04 21:31
My mistake: actually, Franz do change the style of Whatsapp Web to fit the screen.

The problem is the same as the notification: the class name used in style changed because Whatsapp uses generated class names (and thay change from time to time).

The easiest way to fix it is opening the file `service.css` (in the same folder the webview.js is) and changing it to:

```css
#app > div > div {
  width: 100vw !important;
  height: 100vh !important;
  top: 0 !important;
}

._1Wk6A ._3YewW._31v_P._2Ptrm {
  display: none;
}
```

```

**Comment by Marniac95** [comment] 2021-03-04 21:37
Man, you're unbelievable. This is superb work, all fixed! Window back to being 100% sized and badge showing the notification count for chats, not messages. I guess this is just a personal choice, but I rather have the chat number showing, so I can ignore the multiple groups with 100+ messages.

Seriously, thanks for this!

**Comment by faunaman** [comment] 2021-03-08 12:06
Thanks to all for your help and useful tipos/solutions. It has already been fixed on Franz's side and restarting the app was enough. Everything fine right now!

**Comment by faunaman** [comment] 2021-03-08 12:07
Thanks to all for your help and useful tipos/solutions. It has already been fixed on Franz's side and restarting the app was enough. Everything fine right now!

**Closed** 2021-03-08 12:06 UTC

**Comment by jasmines** [comment] 2021-06-17 06:29
Telegram service has started to have the same issue since a couple of days.
Franz 5.7.0 (deb) on Ubuntu 21.04

**Comment by schwixxer** [comment] 2021-07-12 13:49
@JCKodel do you have a similar fix for telegram by chance?

**Comment by Marniac95** [comment] 2022-03-10 18:35
> My mistake: actually, Franz do change the style of Whatsapp Web to fit the screen.
> 
> The problem is the same as the notification: the class name used in style changed because Whatsapp uses generated class names (and thay change from time to time).
> 
> The easiest way to fix it is opening the file `service.css` (in the same folder the webview.js is) and changing it to:
> 
> ```css
> #app > div > div, #app > div > span:nth-child(3) > div > span > div > div {
>   width: 100vw !important;
>   height: 100vh !important;
>   top: 0 !important;
> }
> 
> ._1Wk6A ._3YewW._31v_P._2Ptrm {
>   display: none;
> }
> ```
> 
> This way things will not be broken so easy.

This worked wonders last time, as did the fix for the notification badge. Now, exactly one year later, the same problem popped back up. Is there any reason for this? The previous fix is not working this time.

Thank you!!
