### ISSUE TITLE
Sounds even if disabled

### ISSUE THREAD

**Issue by lucosent** [meetfranz/franz#586] opened 2018-01-17 03:18 UTC
Despite all the notifications are disabled for every services and for the whole Franz, I still hear sounds

**Comment by haraldox** [comment] 2018-01-18 09:54
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

**Comment by haraldox** [comment] 2018-01-18 10:09
probably Duplicate of #509

**Closed by haraldox** 2018-01-18 10:09 UTC

**Comment by haraldox** [comment] 2018-01-18 10:51
related to #460
