### ISSUE TITLE
When downloading an Excel file in Gmail, it turns into a .txt file

### ISSUE THREAD

**Issue by metaregistrar** [meetfranz/franz#77] opened 2017-10-23 12:36 UTC
### Expected Behavior

A client has sent me an .XLSX file, i want to download it to my compuster

### Current Behavior

The file is saved, but without an extension. When i rename it to an .xlsx file, it works and i can open it.

### Steps to Reproduce (for bugs)

1. Receive a file with .xlsx extension as attachment in gmail
2. Download the file from the e-mail message
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta.10
* Operating System and version: macOS High Sierra ver 10.13

**Comment by adlk** [comment] 2017-10-24 11:14
Duplicate of #81

**Closed by adlk** 2017-10-24 11:14 UTC
