### ISSUE TITLE
Notification sounds on Mac, despite 'Do not disturb' ON

### ISSUE THREAD

**Issue by dancsonth** [meetfranz/franz#162] opened 2017-10-28 17:22 UTC
I have enabled do-not-disturb mode on Mac (Sierra 10.12.6) and despite no Franz notifications showing up I get a notification sound every time a new WhatsApp message arrives for example. 

### Possible Solution
I suspect this is due to the fact that this is not the 'system notification sound', but rather coming directly from Franz. (?) However if I remember correctly, in the previous versions of Franz you could chose whether I wanted to have notification sounds (for each channel). This option doesn't seem to be available any longer, hence I suspect it is a direct Franz sound. 

### Context
I think there should be an option to switch sounds per channel, or else it should be off by default, as there are already Mac/Windows system notifications that have their own sound anyway.

### Your Environment
Version 5.0.0-beta.11 (5.0.0-beta.11.135)
Mac (Sierra 10.12.6)

**Comment by Wouter0100** [comment] 2017-10-28 18:29
Possible duplicate of #8 and #90?

**Comment by dancsonth** [comment] 2017-10-28 18:48
Somewhat connected, but to me #8 seems to be already resolved as I can 'disable/enable' notifications per channel in current version. And is asking about not having system notifications i.e. macOS/Windows toasts.

#90 is talking about a disabled service.

Here what I am saying is to disable the sound of Franz app, because system notifications have sounds anyway, so why have both? and as it currently stands, there is no way to mute Franz notifications, as even when I set 'Do not disturb ON', Franz still pings for new messages. 

Does that make sense?

**Comment by adlk** [comment] 2017-10-30 14:00
This is a tricky one. The way we did it in the past was to mute the webview as a whole. While it might work well for DND, it would also disable the audio output an e.g WhatsApp voice recording.

**Comment by batmel** [comment] 2017-10-30 20:28
I still think that the past version, where the whole audio was muted, was better than the current one. especially at work the constant noises due to new messages are really annoying. could the past version, where everything was muted, be an intermediate option until a longterm feature can be found? @adlk

**Comment by dancsonth** [comment] 2017-10-31 00:12
@adlk I agree, that is tricky (and now explains why I never heard WhatsApp video sound or audio messages in previous versions). However I would support @batmel  in saying the constant sound is definitely an issue. 

As a quick fix, that might work over the longer term as well, I would suggest a global sound on/off toggle that can quickly be switched on when wanting to hear sound from content in the apps. See attached screenshot
<img width="325" alt="franz_sound off" src="https://user-images.githubusercontent.com/14165991/32201612-f123a95c-bdcf-11e7-9277-d9bb80e16a9b.png">
<img width="325" alt="franz_sound on" src="https://user-images.githubusercontent.com/14165991/32201613-f149bea8-bdcf-11e7-9914-c43fdadec939.png">

**Comment by adlk** [comment] 2017-11-04 20:02
@dancsonth thanks for the mockup.

I'm planning to add add global mute notifications/mute sounds again. I just need to test a few options as it has to work with future features.

**Closed** 2017-11-18 20:25 UTC
Labels: feature request, os/macOS

**Comment by gres147679** [comment] 2018-07-10 20:08
Any updates on this issue? I saw a mute button was added, but compatibility with DND should still be the way to go, right?

**Comment by sergiufalcusan** [comment] 2020-11-27 15:09
Anyone fixing this ?

**Comment by sungam94** [comment] 2021-01-21 16:28
Why is this not a bug anymore, and why is it closed?

**Comment by kriskhaira** [comment] 2021-02-12 04:01
Hi. I'm wondering if this is related to WhatsApp itself not supporting DND on macOS:
https://www.reddit.com/r/MacOS/comments/aw34ya/macos_mojave_do_not_disturb_does_disturb_me_with/
