### ISSUE TITLE
Back-space character is added sometimes automatically in Slack

### ISSUE THREAD

**Issue by st22** [meetfranz/franz#409] opened 2017-12-06 06:23 UTC
■Environment
　Franz : 5.0.0 beta.14 
　OS : Mac(Darwin Kernel Version 15.3.0)

■scenario
　1. Add Slack app to Franz.
　2. Add some characters in the Slack.
　3. Sometimes, it seems to mingle strange character.
　4. Copy it and paste to sublime-text3, then it look "BS" character.

How can I solve this problem? 
Thenks your help.

**Comment by st22** [comment] 2017-12-06 06:29
I add screen photo.
@Slack
![image](https://user-images.githubusercontent.com/1405922/33647647-810b8b8a-da99-11e7-909a-bc3684156d41.png)

@Sublime-text3
![image](https://user-images.githubusercontent.com/1405922/33647809-3bd8b636-da9a-11e7-90d0-56a88eb309b1.png)

**Comment by adlk** [comment] 2017-12-11 09:39
@koma-private is this something you can reproduce?

**Comment by koma-private** [comment] 2017-12-11 11:22
Although I've not experienced this issue as for daily use of Slack, I have similar problems regarding character encoding when using GitHub via Franz.

Env :
* Inputting Japanese character (UTF-8) by [Google Japanese Input](https://www.google.co.jp/ime/)
* latest Franz & Mac OS
* GitHub recipe

Problem :
An Unicode special character � = "REPLACEMENT CHARACTER" (U+FFFD / 0xEFBFBD) is occasionally inserted to Japanese messages 

![github_error](https://user-images.githubusercontent.com/20257214/33828700-7f70dd50-deb0-11e7-8d30-10e499c8e70e.png)

**Comment by koma-nain** [comment] 2017-12-11 14:38
@st22
I’m now trying to reproduce this issue. Now I have some questions as follow :
1. Does this problem occur only when your using Slack? What about the other recipes?
2. What kind of IME do you use? (System default?)
3. It seems BS characters will be inserted in your environment only when your starting new line. Isn’t it?

**Comment by st22** [comment] 2017-12-13 14:50
@koma-nain
>Does this problem occur only when your using Slack? What about the other recipes?
Yes, it occurs only when I using Slack.

>What kind of IME do you use? (System default?)
I use Google Japanese Input ( ↓ is screen-photo when I click "About Google Japanese Input" on Mac Book)
![image](https://user-images.githubusercontent.com/1405922/33944140-9bccaede-e05e-11e7-98a0-69ac56f1e0f2.png)

>It seems BS characters will be inserted in your environment only when your starting new line. Isn’t it?
Hmm... 
It seems this problem occurs in that situation, but I don't know it is always.

Best regards.

**Comment by koma-private** [comment] 2017-12-14 15:06
I did several tests.

1. Google Japanese Input is not cause of this issue. I encountered same problem even when I use Mac OS's default IME (Kotoeri)
2. Adding a property webPreferences="defaultEncoding=utf-8" to ServiceWebview doesn't solve this too.
3. I disabled spellcheck function of Franz. I'm not sure this is the cause, but now I continue input testing without spellcheck.

@st22 Do you enable the spellcheck function of Franz?

**Comment by KaiShoya** [comment] 2017-12-15 09:00
Sorry for my poor English.
I have the same problem.

Deleting characters before conversion completes will cause this problem.

**Comment by st22** [comment] 2017-12-15 09:20
Hi, @koma-private 
>Do you enable the spellcheck function of Franz?
I don't use spellcheck function of Franz.
So, as @KaiShoya said, it seems that spellcheck function of Franz is not cause.

Best regards.

**Comment by mroeling** [comment] 2017-12-15 21:06
I think the github recipe problem is not necessarily the same issue as the original one. Let me explain, i'll take github as primary example.

The replacement character is shown every time the utf-8 "parser" encounters a character that can not be shown in utf-8, as the byte-code is not utf-8. FYI, utf-8 has always the same starting bits in a two-byte sequence.
So I guess the editing field in the github recipe is propably in a not-utf-8 setting.

The other problem is about an extra BS character. Although it could also be about mixing character sets, I'm not sure it is. 
@koma-private or @st22 could you recreate a text including this bug and copy this directly into a comment field? I'm hoping to be able to reproduce the issue using the text you generate. Perhaps the combination of the "round-dot" character and the EOL character(s) might be the clue we're looking for.

**Comment by koma-private** [comment] 2017-12-16 10:50
I confirmed below :
* Spellcheck function is not the cause.
* Character encoding of GitHub recipe is utf-8, so it's no problem too.

I found the method for reproducing bug.
When IME mode is enabled, you can delete the characters in the middle of converting by hitting delete or backspace key.
And It will also cancel the IME mode to hit them when the input buffer has only 1 character
but this operation will cause the bug with Franz.

![ime_test](https://user-images.githubusercontent.com/20257214/34069724-fa7b9f34-e299-11e7-8fe7-c0a4882bc4f7.gif)

**Comment by koma-private** [comment] 2017-12-16 11:06
Although I cannot see these special characters in Franz, it produce an error to send a "fake" blank message made by the same key operation as explained above.

<img width="435" alt="2017-12-16 19 58 08" src="https://user-images.githubusercontent.com/20257214/34069836-7d8e9f5a-e29c-11e7-9b42-787db60c8f85.png">

**Comment by haraldox** [comment] 2018-01-15 15:07
closing this for now as this is a known issue in electron ... feel free to reopen the issue with any questions or comments!

**Closed by haraldox** 2018-01-15 15:07 UTC
Labels: more information required

**Comment by h6ah4i** [comment] 2018-06-07 02:54
Electron v2.0 has been fixed the upstream issue, but Franz still uses Electron v1.8.4. When will Franz move to use v2.0.x ...?

https://github.com/electron/electron/issues/9173
