### ISSUE TITLE
After waking computer from sleep, active services display blank grey screen

### ISSUE THREAD

**Issue by brendanjones** [meetfranz/franz#593] opened 2018-01-18 09:25 UTC
Version Version 5.0.0-beta.15 (5.0.0-beta.15.607)
MacOS 10.13.2

After computer sleep, and Franz was already open before the sleep, any services that were active before the computer was sent to sleep display a blank grey window.
- The service appears to be active, because the service icon is coloured
- Refreshing the service activates it again
- Any services that weren't active activate just fine, this issue is only for services that were active already before the computer was put to sleep.
- This is not service specific, because it happened to all my different active services.

Example screenshot of 'inactive' active service:

![screen shot 2018-01-17 at 3 05 37 pm](https://user-images.githubusercontent.com/16049594/35046657-ef6747e4-fb97-11e7-9c4f-cae3414c40a6.png)

**Comment by haraldox** [comment] 2018-01-18 09:51
Duplicate of #594

**Closed by haraldox** 2018-01-18 09:51 UTC

**Comment by brendanjones** [comment] 2018-01-18 10:01
Ah, sorry.

**Comment by haraldox** [comment] 2018-01-18 10:12
@brendanjones don't be, it's a super issue, aggregating all the previous issues

**Comment by brendanjones** [comment] 2018-01-18 10:14
Well yeh, but I should have searched and seen those other issues. Instead I was lazy and you had to mark it as duplicate.

**Comment by haraldox** [comment] 2018-01-18 10:15
@brendanjones the super-issue was created just now
