### ISSUE TITLE
"Launch Franz on start" option does not persist

### ISSUE THREAD

**Issue by fahrenhe1t** [meetfranz/franz#127] opened 2017-10-25 20:46 UTC
When clicking the Settings button, and going to the settings tab, I click the "Launch Franz on start" button.  Then I click the X to close the settings.  While Franz is running, the option stays checked.  However if I quit Franz, or reboot, the option is unchecked and Franz does not auto-load.

![franz_launch](https://user-images.githubusercontent.com/33104153/32022310-325c4a64-b993-11e7-822d-cab5ce45bf03.png)

* Franz Version used: 5.0.0-beta.11
* Operating System and version: Windows 10 [Version 10.0.16299.19]

**Comment by treiboll** [comment] 2017-10-26 06:55
It seems to be the same problem for the setting "Minimize Franz to system tray".

**Comment by adlk** [comment] 2017-10-26 18:55
Thanks for reporting this.

I'm currently using the built in electron autostart option but I'm not really satisfied how it works as there are some issues with it. eg #17 #79 

Might use node-auto-launch again as it did a much better job with previous Franz versions.
https://github.com/Teamwork/node-auto-launch

**Comment by adlk** [comment] 2017-10-26 18:57
duplicate of #17

**Closed by adlk** 2017-10-26 18:57 UTC
