### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dominiquini** [meetfranz/franz#1924] opened 2020-11-14 23:10 UTC
**Describe the bug**
The application crashs when I try to open.

**To Reproduce**
1. Click in Franz icon on the start menu
2. See the error window

**Expected behavior**
The application must start

**Screenshots**
![Franz_eAF9PGvvXS](https://user-images.githubusercontent.com/1180808/99158766-2a90c980-26b5-11eb-9109-2a629f3c7d9a.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 - Version 2004 (OS Build 19041.610)
 - Version 5.6.0

**Additional context**
I updated the application from 5.6.0-beta-1. It went back to work when I downgraded to the previous version!

Thanks.

**Comment by Tantawi** [comment] 2020-11-15 00:52
Same issue here, but no error message, just the app process hanging for osme reason and nothisng shown on screen. I also updated from 5.6.0-beta-1 which was working fine. (deb package, Ubuntu 20.10 (Wayland))

**Comment by isness** [comment] 2020-11-15 09:25
Same here, on Ubuntu 20.10:

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/tmp/.org.chromium.Chromium.vGhFP9'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/Franz/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Franz/resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)
`

**Comment by JCKodel** [comment] 2020-11-15 11:01
Same here

![image](https://user-images.githubusercontent.com/379339/99183188-c3a4fc00-2718-11eb-9a3d-d799b40805fc.png)

**Comment by kudlatyamroth** [comment] 2020-11-15 14:31
same here on Manjaro with AUR package franz-bin:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/tmp/.org.chromium.Chromium.qhWvnz'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/usr/lib/franz/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/franz/resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)

(franz:15478): Gtk-WARNING **: 15:26:38.030: Theme parsing error: gtk.css:2:33: Failed to import: Error opening file /home/kudlaty/.config/gtk-3.0/window_decorations.css: No such file or directory
```

**Comment by EricMaGo** [comment] 2020-11-15 17:26
Same in Ubuntu 20.04
![Screenshot from 2020-11-15 18-25-10](https://user-images.githubusercontent.com/19272495/99191873-fd552180-276f-11eb-8cc5-44b61273ac34.png)

Any hints to why this happens?

**Comment by spyfly** [comment] 2020-11-15 18:15
Getting the same error after upgrading from the latest stable release 5.5.0 to 5.6.0 on Ubuntu 20.10
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/tmp/.org.chromium.Chromium.JHT4ez'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/Franz/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Franz/resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)
```

**Comment by RJVB** [comment] 2020-11-15 21:49
Same here with a local build:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/tmp/.org.chromium.Chromium.ZCj1iY'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/Franz/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Franz/resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)
```

Note the node-`mac`-permissions bit: assuming this refers to Mac(intosh) computers (and not the MAC address), what business do MSWin and Linux builds have running that code?!

**Comment by RJVB** [comment] 2020-11-15 22:23
Update: the issue indeed disappears after reverting #7606493e.

**Comment by Antauri** [comment] 2020-11-16 06:57
Same here and I'm a paying user ...

**Comment by dominik59** [comment] 2020-11-16 06:59
Same here.
![obraz](https://user-images.githubusercontent.com/12308040/99221846-ad16a780-27e1-11eb-8292-b71b94be13e9.png)

**Comment by dominik59** [comment] 2020-11-16 07:05
Same here:
![obraz](https://user-images.githubusercontent.com/12308040/99222209-5e1d4200-27e2-11eb-9afe-752e5c9dfadf.png)

**Comment by EricMaGo** [comment] 2020-11-16 07:55
> Update: the issue indeed disappears after reverting #7606493e.

Any hint in how to do it?

**Comment by RJVB** [comment] 2020-11-16 09:49
>> Update: the issue indeed disappears after reverting #7606493e.
>
>Any hint on how to do it?

You need to
- set up your computer for building this application from source following the instructions
- check out this repository and change into the working copy directory. Use `git clone --shallow-since 01-11-2020` to skip most of the commit history that you are not going to need.
- do something like 
```
> git checkout -b tempfix
> git revert --no-edit 7606493e
```

- follow the instructions to build, ending with `npm run build` to get the installer media for your platform (will be in the `out` directory).

This will take quite a bit of time depending on your CPU speed and internet bandwidth, and probably require hundreds of megabytes of disk space.

**Comment by marco-monforte** [comment] 2020-11-16 09:59
Same on Ubuntu 18.04 with the latest release

**Comment by Jpfonseca** [comment] 2020-11-16 11:25
> Same here:
> ![obraz](https://user-images.githubusercontent.com/12308040/99222209-5e1d4200-27e2-11eb-9afe-752e5c9dfadf.png)

Can confirm the issue is present in the version 5.5.0 of the Aur package... 
I am using Wayland.

**Comment by RJVB** [comment] 2020-11-16 13:22
>Can confirm the issue is present in the version 5.5.0 of the Aur package... 

5.6.0 you mean I presume?! (Look at the version given at the bottom of the settings dialog, not the version of the Arch package!)

**Comment by rohsyl** [comment] 2020-11-16 13:52
Same error with after updating to 5.6.0
![image](https://user-images.githubusercontent.com/18440665/99260167-54fc9700-281b-11eb-8183-78c9b3c3e145.png)

**Comment by evanhowington** [comment] 2020-11-16 14:41
Same issue here running Pop!_OS 20.10.  
Fails on load when the gui says "Looking for Sisi" , then something along the lines of "straddling the unicorn"

I just kept opening it because it was saying different things and eventually it loaded up completely and started to run.

**Comment by RJVB** [comment] 2020-11-16 16:06
>Fails on load when the gui says "Looking for Sisi" , then something along the lines of "straddling the unicorn"
>I just kept opening it because it was saying different things and eventually it loaded up completely and started to run. 

I don't know about the others but I never got to see a window. Did you get the same error on the terminal?

**Comment by evanhowington** [comment] 2020-11-16 16:09
> Fails on load when the gui says "Looking for Sisi" , then something along the lines of "straddling the unicorn" I just kept opening it because it was saying different things and eventually it loaded up completely and started to run.
> I don't know about the others but I never got to see a window. Did you get the same error on the terminal?

I never attempted to load through terminal.  Sorry I can't offer any more information.  The window was very brief, short enough to not really be able to time a screen shot.

**Comment by Jpfonseca** [comment] 2020-11-16 17:16
> Can confirm the issue is present in the version 5.5.0 of the Aur package...
> 5.6.0 you mean I presume?! (Look at the version given at the bottom of the settings dialog, not the version of the Arch package!)

I am having the issue in version 5.6.0: 
[Here is the package build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=franz)
Sorry for the mistake.

**Comment by deanhouseholder** [comment] 2020-11-16 17:24
I downgraded to this version and got it working:

https://github.com/meetfranz/franz/releases/tag/v5.6.0-beta.1

**Comment by Jpfonseca** [comment] 2020-11-16 17:38
> I downgraded to this version and got it working:
> 
> [`v5.6.0-beta.1` (release)](https://github.com/meetfranz/franz/releases/tag/v5.6.0-beta.1)



Based on that I just checked the differences between the versions :
[Comparsison between 5.6.0 vs 5.6.0-beta.1](https://github.com/meetfranz/franz/compare/v5.6.0-beta.1...v5.6.0)



> Update: the issue indeed disappears after reverting #7606493e.

Seems that the issue is really related with  the Mac permissions :/ .

**Comment by deanhouseholder** [comment] 2020-11-16 17:44
> > I downgraded to this version and got it working:
> > [`v5.6.0-beta.1` (release)](https://github.com/meetfranz/franz/releases/tag/v5.6.0-beta.1)
> 
> Based on that I just checked the differences between the versions :
> [Comparsison between 5.6.0 vs 5.6.0-beta.1](https://github.com/meetfranz/franz/compare/v5.6.0-beta.1...v5.6.0)
> 
> > Update: the issue indeed disappears after reverting #7606493e.
> 
> Seems that the issue is really related with the Mac permissions :/ . As the beta didn't include them ...

I get the same error on Windows 10.

**Comment by mastercko** [comment] 2020-11-16 21:11
Same here. Getting this error on launch on Windows 10.

**Comment by jasmines** [comment] 2020-11-17 08:25
Not starting on Ubuntu 20.10 KDE:

 JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/tmp/.org.chromium.Chromium.N8nA98'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/Franz/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Franz/resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)

(franz:138106): Gtk-WARNING **: 08:01:00.895: Theme parsing error: gtk.css:1:107: Failed to import: Errore nell'aprire il file ~/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right.css: File o directory non esistente

**Comment by EricMaGo** [comment] 2020-11-17 11:16
Issue solved with release 5.6.1 -> https://github.com/meetfranz/franz/releases/tag/v5.6.1

**Comment by gollum23** [comment] 2020-11-17 11:39
I've confirmed that v5.6.1 all works fine in Manjaro KDE

**Comment by Jpfonseca** [comment] 2020-11-17 11:48
> I've confirmed that v5.6.1 all works fine in Manjaro KDE
It is working fine for Arch-Sway(Wayland) too.

**Comment by Antauri** [comment] 2020-11-17 12:31
Well, that was speedy. Paying (Manjaro KDE) customers are happy again :+1: ...

**Closed** 2020-11-21 00:23 UTC
