### ISSUE TITLE
[MAC] Add emoji shortcuts on Whatsapp Services 

### ISSUE THREAD

**Issue by Bheriya** [meetfranz/franz#657] opened 2018-02-06 15:23 UTC
### Expected Behavior

When i'm typing ";)" i would like to see the emoji not the caracteres

### Current Behavior
When im typing ";)" or something like that ":)", they should be replaced by the corresponded emojis at shorcuts who was saved in my mac. It doesn't work on Whatsapp.
On Messenger, he uses default ones.

### Screenshots (if appropriate):

<img width="78" alt="screen shot 2018-02-06 at 16 16 23" src="https://user-images.githubusercontent.com/36199134/35867435-ffaed3ac-0b59-11e8-8861-9ac7aa0fb688.png">

### Your Environment
* Franz Version used: Version 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: MacOS High Sierra 10.13.3

**Comment by haraldox** [comment] 2018-02-13 15:11
this is something that not even whatsapp does in their official version ... will maybe make its way to a future release of Franz, but non guarantees!

**Comment by haraldox** [comment] 2018-02-13 15:12
Duplicate of #25

**Closed by haraldox** 2018-02-13 15:11 UTC
