### ISSUE TITLE
Feature Request: Categories and Icons

### ISSUE THREAD

**Issue by devcline** [meetfranz/franz#415] opened 2017-12-07 04:43 UTC
### Feature Description
- Somekind of categories.
- Changing icons of the services

### Motivation and Context
* Too many accounts its really a mess. 
* It will let franz to be more organized with services

OS: windows 10
VER: franz 5

ps: If its not possible can we launch franz second time?
Thank you

**Comment by BrianGilbert** [comment] 2017-12-07 05:00
I've been talking with @adlk about this for a while now, we're trying to work out the best approach to contexts.

Here is my initial mockup from a few months ago, but I think we came up with a simpler approach earlier this week. We'll be digging in a bit deeper on the week of Dec 18th, but development may still take some time.

[Franz.pdf](https://github.com/meetfranz/franz/files/1537845/Franz.pdf)

This is the idea from the meeting earlier in the week, a service gould be added to multiple groups, and you switch between the group you want active by clicking the group icon.

[2017-12-07 Groups.pdf](https://github.com/meetfranz/franz/files/1537868/2017-12-07.Groups.pdf)

**Comment by adlk** [comment] 2017-12-11 09:35
This is actually a duplicate of #243 

@BrianGilbert can you merge you comment into the main issue?

Ad icons: there is not an issue on github yet but I already have started with an implementation. I'm not sure if it will make it into beta 15 but it should be ready with beta 16 latest.

I'm going to close and merge this issue.

**Closed by adlk** 2017-12-11 09:35 UTC
