### ISSUE TITLE
[request] debian and fedora repositories.

### ISSUE THREAD

**Issue by Ptero-4** [meetfranz/franz#743] opened 2018-02-28 01:55 UTC
Hi. I recently installed the Franz client and it's quite a nice application but I would like if a debian/ubuntu and a fedora repositories were set up so that installing and updating could be handled from the app store and update manager.

**Comment by haraldox** [comment] 2018-02-28 13:56
Duplicate of #647

**Closed by haraldox** 2018-02-28 13:56 UTC
Labels: os/linux
