### ISSUE TITLE
Allow custom icons for any service

### ISSUE THREAD

**Issue by siparker** [meetfranz/franz#482] opened 2017-12-18 16:19 UTC
I would like to be able to add my own icons for each service. 

### Feature Description
Some services, specifically Whatsapp and FB messenger, show a single icon and you need to hover to see which account is which when you have multiples. I would like to be able to add my own icon for these services on a per service basis so can easily differentiate between them. 
### Motivation and Context
* simplifies usage when there are multiple services of the same type
* This should improve useability for power users when they ahve more than 2 or 3 of a single service type

**Comment by adlk** [comment] 2017-12-19 13:07
Duplicate of #291

**Closed by adlk** 2017-12-19 13:07 UTC
