### ISSUE TITLE
no icon for app under Linux

### ISSUE THREAD

**Issue by peter-schaefer** [meetfranz/franz#604] opened 2018-01-24 07:26 UTC
Installing Franz 5.0.0-Beta 13 there is no icon for Franz under elementary OS.

$ grep Icon /usr/share/applications/franz.desktop 
Icon=franz

So I put Franz/build-helpers/images/icon.png to /usr/share/icons/franz.png and it works like charme.

Maybe Franz/build-helpers/images/icon.png should be renamed or copied and installed into /usr/share/icons/

HTH

**Comment by haraldox** [comment] 2018-01-25 10:54
thanks for bringing that workaround to our attention

What Linux version are you using exactly?

**Comment by peter-schaefer** [comment] 2018-01-25 12:36
$ uname -a
Linux ************ 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

https://elementary.io/de/

Elementary is something like the idiot's choice of desktop linux - and it works pretty well, I have to admit.

By the way, the icon for the tray is black and black is the tray in elementary, if you open a window - so there is no icon to be seen.
You should think about a blue or grey icon set for the tray. Blue should look pretty well.

https://github.com/meetfranz/franz/blob/master/src/assets/images/tray/linux/tray.png

**Comment by alecive** [comment] 2018-01-25 13:34
@haraldox this is true for any linux desktop. See https://github.com/meetfranz/franz/issues/233

**Comment by peter-schaefer** [comment] 2018-01-25 14:11
> @haraldox this is true for any linux desktop. See #233

Haven't seen that one. Thank you.

**Comment by haraldox** [comment] 2018-02-14 14:13
@alecive thanks for the clarification! linux testing is on our list, but we appreciate the community's help in investigating the source of the icon issues under Linux as well as fixing them :)

Duplicate of #233

**Comment by haraldox** [comment] 2018-02-14 14:13
Duplicate of #233

**Closed by haraldox** 2018-02-14 14:13 UTC
Labels: os/linux, tmp/icon
