### ISSUE TITLE
Franz Helper memory hog

### ISSUE THREAD

**Issue by erisol** [meetfranz/franz#184] opened 2017-10-31 12:37 UTC
https://imgur.com/a/x5KAr

Franz Helper is using absurd amounts of memory.

Services used:
Gmail x 2
Outlook 365
Slack x 2
Messenger
Google calendar
Toggl

**Comment by adlk** [comment] 2017-10-31 13:32
Duplicate of #15

**Closed by adlk** 2017-10-31 13:32 UTC
