### ISSUE TITLE
Provide zoomIn shortcut alias

### ISSUE THREAD

**Issue by vbuberen** [meetfranz/franz#54] opened 2017-10-21 21:12 UTC
On Windows with Franz 5.0.0-beta 10 user can make scale smaller with Ctrl + `-`, but can`t scale back with Ctrl + `+` keys.

**Comment by adlk** [comment] 2017-10-22 12:27
Are you using an english keyboard?

**Comment by vbuberen** [comment] 2017-10-22 14:05
Yes, standard keyboard with 102 keys. Language is also English when I try to scale content.

**Comment by alexdevero** [comment] 2017-10-24 10:22
There is also an issue on HIDPI monitors caused by electron dependency.

**Comment by adlk** [comment] 2017-10-24 14:49
I did a test with a keyboard and it works with `ctrl+shift+=`. I will do a test if it's possible to create an alias for it.

@alexdevero What HDPI issue do you mean? I believe that a separate issue would be most appropriate for it to be able to keep track of it as I'm going to close this issue as soon as I've deployed a fix.

**Comment by alexdevero** [comment] 2017-10-24 15:24
@adlk There is an issue in Electron with scaling on HIDPI screns - https://github.com/electron/electron/issues/10862, https://github.com/electron/electron/issues/9477. This issue is causing wrong scaling of the content and users on devices with HIDPI screens has to zoom out to fix this.

Example:
![hidpi-issue](https://user-images.githubusercontent.com/4237724/31951994-cf697692-b8df-11e7-8076-a4ad67d5e07f.PNG)

Take a look at my CMD (green on the left) and then on the content of the electron app window. Compare text in the nav bar with the content of the dev tools.

**Closed** 2017-10-25 07:52 UTC
Labels: enhancement

**Comment by vbuberen** [comment] 2017-10-25 08:57
@adlk It is not that obvious to use `shift` too. All web-browsers work without it. Thanks for taking care.
