### ISSUE TITLE
Clicking a link in an Outlook email opens a small blank Franz window instead of opening my browser.

### ISSUE THREAD

**Issue by goduran** [meetfranz/franz#608] opened 2018-01-24 16:43 UTC
### Expected Behavior

When clicking a link in an Outlook email, it should open in my browser.

### Current Behavior

A smaller Franz window opens with no title and no content. Sometimes this window will load content after a while, but is generally uncomfortable since it is a stripped-down version of a browser. Using right click-> open link generally works.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
5.0.0-beta.14 release 1.7.9
* Operating System and version:
Windows 10 Home, build 16299

**Comment by haraldox** [comment] 2018-01-25 10:46
Duplicate of #577

**Closed by haraldox** 2018-01-25 10:46 UTC
