### ISSUE TITLE
Tweedeck white screen before login (blank screen)

### ISSUE THREAD

**Issue by nik0lai** [meetfranz/franz#461] opened 2017-12-13 17:42 UTC
I recently download and installed Franz. I activated four services: WhatsApp, facebook messenger, Gmail inbox and TweetDeck. However, TweetDeck shows a blank screen after clicking Log in.

### Expected Behavior

Be able to log in to TweetDeck

### Current Behavior

After clicking Log in on TweetDeck (before giving my username and password) the screen goes white.

### Screenshots (if appropriate):
Before clicking Log in
![image](https://user-images.githubusercontent.com/11561730/33953310-4d172152-e013-11e7-9612-f0904f252b35.png)
After clicking Log in
![image](https://user-images.githubusercontent.com/11561730/33953287-397b5122-e013-11e7-92c0-febc78c1a993.png)

### Steps to Reproduce (for bugs)

I don't have steps to reproduce as this is happening since I installed Franz.

### Your Environment

* Franz Version used: 5.0.0-beta.14 Release: 1.7.9 / linux / x64
* Operating System and version:  Ubuntu 16.04

**Comment by adlk** [comment] 2017-12-14 09:34
Duplicate of #253

**Closed by adlk** 2017-12-14 09:34 UTC
