### ISSUE TITLE
Hipchat doesn't stay logged in.

### ISSUE THREAD

**Issue by llovelock** [meetfranz/franz#679] opened 2018-02-13 10:50 UTC
### Expected Behavior
Hipchat should remain logged in much like every other service.

### Current Behavior
Upon quitting and re-opening Franz, Hipchat is logged out, and credentials are forgotten every time.

### Your Environment
* Franz Version used: 5.0.0-beta. 14.451
* Operating System and version: Mac OSX 10.13

**Comment by haraldox** [comment] 2018-02-13 12:40
Duplicate of #113

**Closed by haraldox** 2018-02-13 12:40 UTC
