### ISSUE TITLE
HipChat cmd-c not working

### ISSUE THREAD

**Issue by ylluminate** [meetfranz/franz#50] opened 2017-10-20 23:37 UTC
I've found that cmd-c is not working to copy content in HipChat content. Right click and then selecting Copy works, but cmd-c is not.

**Comment by Kotys** [comment] 2017-10-21 14:09
Hello, I'm MacOS High Sierra (10.13).
This bug appears on all my services (HipChat, FB Messenger, WhatsApp).
I think, it's not service relevant, it will be something global for webview and event handlers.

I'll try to find solution and send PR today.

**Comment by adlk** [comment] 2017-10-21 17:26
Duplicate of #33

**Closed by adlk** 2017-10-21 17:26 UTC
