### ISSUE TITLE
Several languages to Franz Dictionary 

### ISSUE THREAD

**Issue by thomquert** [meetfranz/franz#198] opened 2017-11-02 16:20 UTC
Hey Franz! I am using Version 5.0.0-beta.11 (5.0.0-beta.11.135)
I talk in English & French on my WhatsApp and it seems like you can only choose one language at a time in the Settings. I chose English. It is annoying to have the red doted line under every word I write in French. 

Keep it up

**Comment by adlk** [comment] 2017-11-03 09:36
Duplicate of #92

**Closed by adlk** 2017-11-03 09:36 UTC
