### ISSUE TITLE
extreme ram usage

### ISSUE THREAD

**Issue by JAicewizard** [meetfranz/franz#480] opened 2017-12-17 16:25 UTC
Arch linux(build 17 December) + franz-bin(from AUR, beta 13)

Having franz open with just discord, whatsapp, gmail, and outlook, franz and all of its child processes are using 1.1 GiB. 
This is because you are using electron for the desktop application.
to solve this you could use a more native API, consider QT for this, it has a webview for the web pages.
This would use a lot less RAM for the same effect, and your application would, probably, become more energy efficient and faster.

Note that all the games I play(WOT and CSGO mainly) use about as much RAM as this 4 html page setup you created.

**Comment by rwkyyy** [comment] 2017-12-18 13:49
@JAicewizard I think it's related to how much RAM your device has.

for example, on my mbp with 8gb, and 4 services, it would use around 400-600mb; on my other mbp with 16 gb ram, it uses 1.1 gb ram (atm).

I think it's mostly how the OS handles the app, but I do agree on improvements 👍

**Comment by JAicewizard** [comment] 2017-12-18 17:58
hmm, this is why I don't like atom (and JS). I have about 12 GiB of RAM and I'd like to not have 10% go to 4 webviews.
atom can be used in a good way, vsCode, for example, uses about 500 MiB of RAM.
not great but still quite good for a cross-platform application.
keep working on improvements and I hope that any issues will be resolved.
maybe a better cross-platform GUI api/platform arrives with better memory management.

**Comment by Neules** [comment] 2017-12-19 12:11
Yeah, same here with macbook 4 Gb RAM, franz uses 497 Mb RAM.

**Comment by adlk** [comment] 2017-12-19 13:05
Duplicate of #15

**Closed by adlk** 2017-12-19 13:05 UTC

**Comment by si266** [comment] 2020-04-08 11:48
For me Franz uses between 2 to 4GB of RAM constantly. I love the app, but I'll have to delete it...

<img width="392" alt="image" src="https://user-images.githubusercontent.com/60767727/78780873-4e48a000-796d-11ea-819a-94114d58cec7.png">
