### ISSUE TITLE
Links in Skype are won't open in the default browser

### ISSUE THREAD

**Issue by timorunge** [meetfranz/franz#333] opened 2017-11-23 17:03 UTC
### Expected Behavior
By clicking a link in Skype the link should actually open in a new browser window / tab of the default browser of the OS. 

### Current Behavior
At the moment a new Franz is opening the clicked link in a new Franz-Window.

### Screenshots (if appropriate):
<img width="1680" alt="screen shot 2017-11-23 at 17 58 38" src="https://user-images.githubusercontent.com/1560363/33183551-95f2a6da-d078-11e7-9393-6679832dfcf1.png">

### Steps to Reproduce (for bugs)

1. Create a Skype service, login in
2. Post a link and click it
3. A new Franz window will open

### Your Environment
* Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: macOS Sierra, 10.12.6 (16G1036)

**Comment by Wouter0100** [comment] 2017-11-23 21:47
This issue would be more on it's place in https://github.com/meetfranz/recipe-skype. This one is related to meetfranz/recipe-skype#2 I suppose.

**Comment by adlk** [comment] 2017-11-27 11:01
@timorunge Thanks for reporting this issue and @Wouter0100 thanks for pointing to the right direction :)

I've made an update to skype a couple of days ago and it seems that I went a little too far. Further updates will be posted in the skype recipe issue

**Comment by haraldox** [comment] 2018-01-15 12:24
Duplicate of #194

**Closed by haraldox** 2018-01-15 12:24 UTC
