### ISSUE TITLE
MacOS - Absurdly loud notification volume when opening macbook lid

### ISSUE THREAD

**Issue by hurlsworth** [meetfranz/franz#928] opened 2018-04-25 14:56 UTC
Each morning when I open my macbook lid (after being closed for 8 hours), I get a Discord notification sound seemingly louder than max volume. It is always too loud and startling. This happens consistently every morning. The volume of the computer is set around 20%. Immediately afterwards, regular notifications start coming through at the expected volume. 

Of note: I have an SD card in my macbook as storage which I believe prevents the computer from fulling going to sleep, if that is useful info.

Expected Behavior -- If notifications have accumulated while the lid was shut, once the lid is opened, their sound should be played at the system volume, the same volume the notification prior to closing the lid, and immediately after the too-loud notification, is played at. 

Current Behavior -- The first notification (in this case Discord's) when opening the lid is at max volume or higher. It seems to clip and distort, it's so loud. 

Steps to Reproduce
1. Use Franz and Discord normally
2. Close lid at end of night (Note: have SD card permanently present in macbook for extra space that might prevent computer going to sleep.)
3. Open lid in the morning
4. Witness very loud discord notification sound

Context
I want to open my computer and get to work as normal. I work in a quiet office environment and my laptop volume is always set very low. Franz appears not to respect this system volume with the initial notification when opening the lid each morning, announcing my loud and inconsiderate presence. My current solution, which I usually forget to do, is to close Franz at the end of the night and re-open in the morning. 

### Your Environment

* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: macOS High Sierra 10.13.3 (17D102). Using early 2015 Macbook Pro 13-inch, Retina.

**Comment by derdaani** [comment] 2018-09-04 09:30
Same here, but without closing the macbook.

Bluetooth speakers connected, listening to music. When I receive a message in Franz (WhatsApp), the volume suddenly becomes ridiculously loud. Almost died of a heart attack twice today...

Franz Version used: Version 4.0.4
Operating System and version: macOS High Sierra 10.13.6 (17D102). Using 2017 Macbook Pro 15-inch.

**Closed** 2018-11-19 08:49 UTC
Labels: wontfix

**Comment by hurlsworth** [comment] 2018-11-19 16:04
Is it useful information to know that this is still periodically occurring?

**Comment by Superbird11** [comment] 2019-05-16 01:05
As of 5/15/2019 this is occurring, nearly every time I open my laptop. I feel like the cause is multiple notification sounds "stacking" on each other and playing all at once when I open my laptop after a long time in sleep mode.

**Comment by SinjonC** [comment] 2019-08-24 17:35
Its amazing that this has been going on for over a year and its still been an issue for me. Glad i'm not the only one experiencing it. I guess it either hasn't been brought up to the Discord Team's attention or its niche enough that they decided it wasn't worth the hassle to fix. I haven't been using my Macbook nearly as much so I haven't needed to deal with this as much (plus i've had my discord status permanently set to 'Do No Disturb' which turns off the notification sounds entirely), but I figure I might try deleting and re-installing Discord eventually. I hope that'll solve the problem!

**Comment by cabletie** [comment] 2020-10-17 01:54
... and still a problem even now.
Guys guys guys! Please fix it!

**Comment by dotms** [comment] 2021-06-17 17:41
For what it's worth, I also experience this exact same behavior on the regular Discord client. Consistently, every day after sleep.

**Comment by CptSpaceToaster** [comment] 2021-06-19 19:03
This is Incredibly rage-inducing. It sounds like the notification sound effect is queued up while the mac is sleeping (lid is closed) and every queued notification **plays at once** when the mac comes to. It's so loud, my speakers usually clip, despite the mac's volume being set to 10%-20%.

**Comment by mindflays** [comment] 2021-08-08 09:55
i also _still_ experience this issue, every single time when i open my macbook after it's gone to sleep.

**Comment by otrabalhador** [comment] 2021-09-16 13:24
I also have this problem everytime I open my macbook in the morning.

**Comment by jellyjam14blas** [comment] 2021-09-27 02:04
I have the same problem with my IMac. I'm surprised so many other people have experienced it for so long.

**Comment by iirftw** [comment] 2021-09-30 11:03
m1 MacBook same issue but seems to be a discord issue not a Franz issue as the same behaviour happens with the standard client.

**Comment by CptSpaceToaster** [comment] 2021-11-04 16:27
This is likely an issue with vanilla discord... and/or how mac processes queued notifications sound effects while the device is asleep. I've been able to repeat this _without_ franz... so while the issue could be duplicated in both places... it seems rude to keep pinging the developers with comments on an issue that's likely an issue with Discord itself.

I've gone to discords support portal once... but like any belligerent support portal... they demanded a long and complicated list of steps to reproduce and because it involves putting the mac to sleep, I never got around to testing the exact conditions to repeat the awful noise.

So before I take another dive trying to report this issue _to Discord_ it might make sense to try and cobble together some steps to reproduce.

I think it's as simple as
1. Log into discord as User A on a mac.
1. Ensure that User A has a notification sound play for direct messages
1. Put the mac to sleep
1. Use a separate device that's logged into discord as User B
1. Send several messages to User A.

I'm currently not sure if that's _enough_ or if users need to have multiple sources of notification sound effects pile up... i.e. one sound for every discord, and new DM... etc...

**Comment by z3braman** [comment] 2022-01-31 02:46
I am having this with my M1 MacBook Air running public beta. I have experienced it for a few months now and tried to revert to regular distro to see if that fixed it but I have not wanted to invest the time to undo the beta installation.
I am happy to hear someone describe it as several notifications piling up at once. And it is distorting the output and is quite loud. It does vary too. Sometimes it's really harsh, sometimes a normal level. As if when there are a lot of notifications they are crazy loud and distorted and when there are only a few it is much quieter and less distorted.

**Comment by hurlsworth** [comment] 2022-01-31 03:15
This is almost surely unrelated to Franz specifically. It seems like the Discord message notifications are stacked on top of each other, each amplifying the waveform of the one prior if you will. I believe this is present in using discord via a web browser as is. I have not tried to reproduce this personally on the discord client. 

I am also not clear if other mac notifications would pile up in the same way but this seems more of a Discord issue because of the number of message notifications that might be more prone to stacking other notifications in other applications.

**Comment by SamuelBeaudoin** [comment] 2022-02-17 20:23
I'm getting the same problem even though I've turned off every single app's notifications. I do have discord installed but I shouldn't be getting notifications from it.
